### ISSUE TITLE
Custom metrics exported by JITServer can be encrypted with SSL/TLS

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9-docs#1000]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/15217

**Overview:**
The custom metrics exported by JITServer and scraped by a monitoring agent like Prometheus can now be secured with SSL/TLS authentication and encryption.

**Release target:**
Eclipse OpenJ9 0.35.0

**Applies to the following JDK versions:**
All Java versions supported by JITServer, i.e. Java 8, Java11, Java17

**Applies to the following platforms:**
All platforms supported by JITServer i.e. Linux X|P|Z

**For new command line options:**

- Option name and syntax: 
*-XX:JITServerMetricsSSLKey=key_file*  and  *-XX:JITServerMetricsSSLCert=certificate_file*
- Purpose: These options specify the name of the files containing the private SSL/TLS key and the SSL/TLS certificate. These files need to be in *.pem* file format.
- Note: Custom metrics exported by JITServer are sent in clear text by default. To secure them with SSL/TLS you need to pass the options mentioned above to the command line of the JITServer process.
- Note: To turn on the export of custom metrics you must specify `-XX:+JITServerMetrics` on the command line at the JITServer process. See the following topic: https://github.com/eclipse-openj9/openj9-docs/blob/master/docs/xxjitservermetrics.md

The xxjitservermetrics.md topic currently says "The data is currently not encrypted."
This needs to be changed to say: The data can be optionally encrypted with SSL/TLS by using *-XX:JITServerMetricsSSLKey=key_file*  and  *-XX:JITServerMetricsSSLCert=certificate_file* options.

We may also want to mention the new options in https://github.com/eclipse-openj9/openj9-docs/blob/master/docs/jitserver.md under "Configuring JITServer technology"

**Comment by Sreekala-Gopakumar** [comment]
Adding a comment so that Esther can assign it to me.
