### ISSUE TITLE
Document JITServer AOT cache memory limit option

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [eclipse-openj9/openj9-docs#1004]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/15775

**Overview:**
The newly added option `-XX:JITServerAOTmx=` can be used to limit the amount of memory used by the JITServer AOT cache.

**Release target:**
Eclipse OpenJ9 0.36.0

**Applies to the following JDK versions:**
All JDKs where JITServer is supported: 8, 11, 17

**Applies to the following platforms:**
All platforms where JITServer is supported: Linux X|P|Z

**New command line options:**
- Option name and syntax: `-XX:JITServerAOTmx=<size>`
- Units for setting: memory size
- Default value: 300 MB
- Purpose: limit the amount of memory used by the JITServer AOT cache.

**Comment by AlexeyKhrabrov** [comment]
@mpirvu @cjjdespres FYI

**Comment by mpirvu** [comment]
Note that this change is not in the upcoming release 0.35.0. The branch for 0.35.0 was created on August 26.

**Comment by Sreekala-Gopakumar** [comment]
I will take this up for 0.36 release.

**Comment by Sreekala-Gopakumar** [comment]
@AlexeyKhrabrov @mpirvu - What does "Default value: no limit" mean in https://github.com/eclipse-openj9/openj9-docs/issues/1004#issue-1400267108? Does it mean that "By default, the amount of memory that an AOT cache can consume at the server is not limited."? This is the current limitation as explained in the existing document, isn't it?(https://www.eclipse.org/openj9/docs/jitserver_tuning/ -> JITServer AOT cache -> Current limitations). We will use the ` -XX:JITServerAOTmx` to specify a particular size i.e. we are not supposed to leave it blank, right? (`XX:JITServerAOTmx= `)

Is there any minimum or maximum size that can be specified for this option? 

Thanks!

**Comment by mpirvu** [comment]
Actually, looking at the code, the current limit is 300 MB:

`size_t JITServerAOTCacheMap::_cacheMaxBytes = 300 * 1024 * 1024;`

There is no minimum value (or option to configure a minimum value)
