### ISSUE TITLE
Change default cache directory on Linux, AIX and macOS

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9-docs#1016]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16256

**Overview:**
On non-Windows, non-z/OS systems, <directory> the default shared cache and snapshot directory is changed from `javasharedresources` to `.cache/javasharedresources` in the user's home directory. The default shared cache and snapshot directory is still `/tmp/javasharedresources/` if `-Xshareclasses:` sub-option`groupAccess` is used, which is unaffected.

**Release target:**
Eclipse OpenJ9 0.36.0

**Applies to the following JDK versions:**
All JDK versions (doesn't affect IBM Java 8)

**Applies to the following platforms:**
AIX, Linux X|P|Z, macOS

**Migration:**

1. If there is no `javasharedresources` directory in user's home, no action is required. 
2. If the `javasharedresources` directory in user's home is empty, the `javasharedresources` directory can be deleted.
3. Users that always use `-Xshareclasses:` sub-options `groupAccess` or `cacheDir=` in the CML won't be affected by this change.
4. User can use `-Xshareclasses:cacheDir=<HomeDir>/javasharedresources/,listAllCaches`(`cacheDir=<HomeDir>` for nonpersistent cache and snapshot) to find the caches (and cache snapshots) in the obsolete default directory. If all the shared caches (cache snapshots) are not useful anymore, use
     1). `-Xshareclasses:cacheDir=<HomeDir>/javasharedresources/,destroyAll` (`cacheDir=<HomeDir>` for nonpersistent cache) to remove all caches.
     2). `-Xshareclasses:cacheDir=<HomeDir>,destroyAllSnapshots` to remove the all snapshots.
5. To remove a particular shared cache (cache snapshot), use
     1). `-Xshareclasses:cacheDir=<HomeDir>/javasharedresources/,name=<cacheName>,destroy`  (use `cacheDir=<HomeDir>` for nonpersistent cache, `destroyAllLayers` for multi-layer cache) to remove the shared cache.
     2). `-Xshareclasses:cacheDir=<HomeDir>,name=<snapshotName>,destroySnapshot` to remove the snapshot.

**Comment by pshipton** [comment]
Changed the release target to 0.36, we haven't branched for this release yet so anything merged in the next few weeks will go into this release.

**Comment by Sreekala-Gopakumar** [comment]
I will look into this. Thanks!
