### ISSUE TITLE
JSR 337 Maintenance Release 4: Java SE 8

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1017]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/15784
https://github.com/eclipse-openj9/openj9/pull/15828

**Overview:**
"JSR 337 Maintenance Release 4: Java SE 8" dictates some changes in Java 8 which are delivered with 0.35 / 8u352.
https://jcp.org/aboutJava/communityprocess/maintenance/jsr337/jsr337-mr4-changes.html

**Release target:**
0.35

**Applies to the following JDK versions:**
Java 8

**Applies to the following platforms:**
All

The doc update should first be delivered in the head stream as usual via Pull Request, and then we can also deliver it to the openj9-docs-0.35.0 branch and re-generate the 0.35 docs. I can help with that part after the Pull Request is merged.

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - After going through the changes specified and the existing OpenJ9 documents, I could identify only one change, Phantom reference, that needs to be updated in https://www.eclipse.org/openj9/docs/gc_overview/#weak-reference-processing. Is there anything else that needs an update in the existing document that you are aware of? 

Thanks!
