### ISSUE TITLE
Change copyright dates for 2023

### ISSUE THREAD

**Issue by doveye** [eclipse-openj9/openj9-docs#1021]
- [ ] The copyright year on all the docs will need updating from 2022 to 2023. Here's a list of things to update from a previous issue (#673), with year updated:

> Update header in all `.md` files to:
> `Copyright (c) 2017, 2023 IBM Corp.` (Don't include 'and others' in search because not relevant in one or two instances.)
> 
> Also in all other source files -
> 
> - `mkdocs.yml`
> - `oj9.css`
> - `requirements.in`
> - `requirements.txt`
> - `*.html` in `theme` dir
> - `*.groovy` (x3)
> 
> Check also for occurrences of `2021, 2022` or similar. (Change to `2017, 2023`)
> 
> Beware of dates in links and release tables (e.g. `jitserver.md`, `openj9_support.md`).

- [ ] While we're changing all those files, we can also change http://openjdk.java.net/legal/assembly-exception.html to https://openjdk.org/legal/assembly-exception.html, as mentioned in https://github.com/eclipse-openj9/openj9/issues/16057.

**Comment by Sreekala-Gopakumar** [comment]
Will do, Esther. Thanks!
