### ISSUE TITLE
Document JITServer AOT cache persistence

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9-docs#1025]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16075

**Overview:**
The new `-XX:+JITServerAOTCachePersistence` option (when JITServer AOT caching has been enabled) instructs the JITServer to periodically save its AOT caches to files, and to load caches from files the first time a client requests a particular named cache. This allows for AOT caches to persist across individual JITServer instances. This should improve performance, and will be especially useful in containerized autoscaling scenarios, when JITServer instances can be expected to be started up and shut down regularly.

**Release target:**
Eclipse OpenJ9 0.36.0

**Applies to the following JDK versions:**
JDK 8, 11, 17 (all supported JITServer JDK versions)

**Applies to the following platforms:**
Linux X|P|Z (all supported JITServer platforms)

**For new command line options:**

- `-XX:[+|-]JITServerAOTCachePersistence`
  - Default: Disabled
  - Purpose: Periodically save the AOT caches held by a running JITServer to files, and also load existing caches from files if a client requests a particular cache, that cache has not already been created, and a corresponding cache file exists in the cache directory
- `-Xjit:aotCachePersistenceMinDeltaMethods=`
  - Default: 200
  - Units for setting: number of methods
  - Purpose: Number of extra AOT methods that need to be added to the JITServer AOT cache before considering a save operation
- `-Xjit:aotCachePersistenceMinPeriodMs=`
  - Default: 10000
  - Units for setting: milliseconds
  - Purpose: Miminum time between two consecutive JITServer AOT cache save operations
- `-XX:JITServerAOTCacheDir=`
  - Default: Empty string (in which case the cache directory is the current working directory of the JITServer)
  - Purpose: Directory that will be used for saving and loading JITServer AOT cache files

**Comment by cjjdespres** [comment]
Attn @mpirvu @AlexeyKhrabrov.

**Comment by AlexeyKhrabrov** [comment]
Should the `-Xjit:` options be documented at all?

**Comment by mpirvu** [comment]
Indeed, we don't have to disclose the -Xjit: options like we do for the -XX: options. However, we can briefly talk about them when we describe how the mechanism works, maybe in `jitserver_tuning.md` document.

**Comment by Sreekala-Gopakumar** [comment]
I will take this up.

**Comment by Sreekala-Gopakumar** [comment]
In the existing document, -Xjit / -Xnojit topic (https://www.eclipse.org/openj9/docs/xjit/), there is a table where we are briefly discussing different parameters that are used with -Xjit. So, would you like me to add the -Xjit: options mentioned in this issue in that table?
Thanks!

**Comment by cjjdespres** [comment]
I'm not sure that we want that, since there are a lot of other `-Xjit:` options that are undocumented. (Unless we want to start documenting them all publicly). Maybe they could be mentioned in the `jitserver_tuning.md` document, like Marius said. The "JITServer AOT cache" section needs to be updated to reflect these changes anyway.

**Comment by mpirvu** [comment]
> So, would you like me to add the -Xjit: options mentioned in this issue in that table?

No, since that table only has a very small fraction of the JIT options. Moreover, these options are for tuning behavior of JITServer tech.

**Comment by mpirvu** [comment]
Documentation was merged
