### ISSUE TITLE
Change default JITServer AOT cache name

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9-docs#1026]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16166

**Overview:**
The default value of `-XX:JITServerAOTCacheName=` is now `default`. It was formerly the empty string (i.e., nameless).

**Release target:**
Eclipse OpenJ9 0.36.0

**Applies to the following JDK versions:**
All versions supported by JITServer (JDK 8, 11, 17)

**Applies to the following platforms:**
All platforms supported by JITServer (Linux X|P|Z)

**Comment by cjjdespres** [comment]
Attn @mpirvu @AlexeyKhrabrov.

**Comment by Sreekala-Gopakumar** [comment]
I will take this up.
