### ISSUE TITLE
Clarify JVMPORT030W and JVMDUMP012E messages

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9-docs#1033]
**Subject:**

Changes:

* Through J9 [commit 504fd6a](https://github.com/eclipse-openj9/openj9/commit/504fd6a3ec4a42177afc0f461fae6a398ce14456) and [issue 16367](https://github.com/eclipse-openj9/openj9/issues/16367), the `JVMPORT030W` message has appended the sentence "Review the manual for the external program to find where the core dump is written and ensure the program does not truncate it."
* Through OMR [commit d9f0697](https://github.com/eclipse/omr/commit/d9f0697ed576b7964a7b7d28b40f4043744c168e) for [issue 6837](https://github.com/eclipse/omr/issues/6837), a new message `JVMPORT049I` is printed before `JVMDUMP012E` when `kernel.core_pattern` is a piped program.

Example output:

```
JVMDUMP032I JVM requested System dump using '/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/core.20221206.214232.76306.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.76329.  Review the manual for the external program to find where the core dump is written and ensure the program does not truncate it.

JVMPORT049I The core file created by child process with pid = 76329 was not found. Review the documentation for the /proc/sys/kernel/core_pattern program "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" to find where the core file is written and ensure that program does not truncate it.

JVMDUMP012E Error in System dump: /openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/core.20221206.214232.76306.0001.dmp
```

**Suggestion:**

It might be worth adding a new documentation page that helps customers interpret these messages and find core dumps for common core_pattern piped programs. For example:

----

# Linux piped core dump processing programs

Many modern Linux distributions and environments have moved to setting `kernel.core_pattern=|$PROGRAM` by default to pipe core dumps to a core dump processing program (e.g. `systemd-coredump`, etc.). This allows for the constraint of per-core dump or all-core dump disk usage, allowing for avoidance of core dump disk exhaustion that may lead to catastrophic application outages.

The message `JVMPORT030W` will be printed in most cases of such configured programs because the JVM cannot find the core dump in the current working directory. However, this warning does not necessarily mean there is any problem producing the core dump; instead, you must review the manual for the specified core dump processing program to find if and where the core dump is produced, and configure the program properly to avoid truncation. A new message `JVMPORT049I` emphasizes this when a piped `kernel.core_pattern` is detected.

You may find the current setting of `kernel.core_pattern` by running one of the following commands; for example:

```
$ cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
$ sysctl kernel.core_pattern
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
```

It is also available in a Java Dump; for example:

```
2CISYSINFO     /proc/sys/kernel/core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
```

For reference, some of the most common core dump processing programs are:

1. `systemd-coredump` (e.g. `core_pattern=|/usr/lib/systemd/systemd-coredump`)
    * By default, dumps go to `/var/lib/systemd/coredump/`
    * Versions before v251 [truncate 64-bit core dumps at 2GB](https://github.com/systemd/systemd/issues/22076). To avoid this, consider updating `/etc/systemd/coredump.conf` to increase `ProcessSizeMax` and `ExternalSizeMax` and reload configuration with `systemctl daemon-reload`. After v251, similar changes are needed if the core dump will be greater than 32GB.
2. `apport` (e.g. `core_pattern=|/usr/share/apport/apport`)
    * By default, dumps go to `/var/crash/` or `/var/lib/apport/coredump/`
    * Default settings should not truncate.
3. `abrt-hook-ccpp` (e.g. `core_pattern=|/usr/libexec/abrt-hook-ccpp`):
    * By default, dumps go to `/var/spool/abrt`
    * Default settings may truncate. Consider updating `/etc/abrt/abrt.conf` to set `MaxCrashReportsSize=0` and restart `abrtd`.
4. Dynatrace rdp (e.g. `core_pattern=|/opt/dynatrace/oneagent/agent/rdp`):
    * The program should pass along the core dump to the underlying core dump processing program as seen in `/opt/dynatrace/oneagent/agent/conf/original_core_pattern`; depending on its value, review the above and the program's manual.

In container environments such as OpenShift, piped core dumps go to the worker node rather than inside the container. One example method to retrieve such dumps for `systemd-coredump` (`|/usr/lib/systemd/systemd-coredump`):

1. To access the core dump, a user with `cluster-admin` superuser privileges is required.
1. Find the worker node of the pod (replace `$PODNAME` and `$NAMESPACE`):
   ```
   oc get pod --namespace $NAMESPACE --output "jsonpath={.spec.nodeName}{'\n'}" $PODNAME
   ```
1. Start a debug pod on the worker node (replace `$NODE` with the result from the previous step):
   ```
   oc debug node/$NODE -t
   ```
1. List available core dumps; for example:
   ```
   # chroot /host coredumpctl
   TIME                             PID        UID   GID SIG COREFILE  EXE
   Wed 2022-08-03 18:52:29 UTC  2923161 1000650000     0  11 present   /opt/java/semeru/jre/bin/java
   ```
1. Find the line for the core dump that was taken, copy that PID, and pass it to the `info` sub-command to search for the dump location; for example:
   ```
   # chroot /host coredumpctl info 2923161 | grep Storage:
       Storage: /var/lib/systemd/coredump/core.kernel-command-.1000650000.08b9e28f46b348f3aabdffc6896838e0.2923161.1659552745000000.lz4
   ```
1. Start a looping output so that the debug pod doesn't timeout:
   ```
   while true; do echo 'Sleeping'; sleep 8; done
   ```
1. Open a new terminal and find the debug pod and namespace; for example:
   ```
   $ oc get pods --field-selector=status.phase==Running --all-namespaces | grep debug
   openshift-debug-node-pwcn42r47f       worker3-debug       1/1     Running            0                  3m38s
   ```
1. Use the above namespace (first column) and pod name (second column) to download the core dump from the worker node from the `Storage` location above, making sure to prefix the Storage location with `/host/`; for example:
   ```
   oc cp --namespace openshift-debug-node-pwcn42r47f worker3-debug:/host/var/lib/systemd/coredump/core.kernel-command-.1000650000.08b9e28f46b348f3aabdffc6896838e0.2923161.1659552745000000.lz4 core.dmp.lz4
   ```
1. After the download completes, in the previous terminal window, type `Ctrl^C` to exit the loop and then type `exit` to end the debug pod.
1. The core dump is now available locally in `core.dmp.lz4`

**Comment by Sreekala-Gopakumar** [comment]
@kgibm @pshipton - This is a part of 0.36.0 release? 
Thanks!

**Comment by doveye** [comment]
This raises the outstanding issue of what to do with OpenJ9 message docs. They are currently in the [IBM docs](https://www.ibm.com/docs/en/sdk-java-technology/8?topic=vm-messages) and haven't been updated for years. I doubt that they can be regenerated using the old method any more.

**Comment by Sreekala-Gopakumar** [comment]
@kgibm - What is the difference between JVMPORT030W, JVMPORT049I, and JVMDUMP012E messages? Under what different scenarios are these messages printed? All three seems related to piped kernel.core_pattern but a clarity on their differences will help me write better. Thanks!

**Comment by Sreekala-Gopakumar** [comment]
@kgibm @pshipton - In the sentence "The core dump is now available locally in core.dmp.lz4", is "core.dmp.lz4" a folder?

**Comment by kgibm** [comment]
> In the sentence "The core dump is now available locally in core.dmp.lz4", is "core.dmp.lz4" a folder?

No, it's a compressed file.

**Comment by kgibm** [comment]
@Sreekala-Gopakumar I don't know how far you want to go in documented what are essentially OpenShift-specific topics (although practically needed by Java-based deployments and not well documented by RedHat) but I also recently published a blog post on how to avoid core dump truncation in OpenShift if the Java process virtual size is greater than 2GB and systemd-coredump version <= 250 is in-use (default on OpenShift 4). Feel free to copy if you'd like: https://community.ibm.com/community/user/wasdevops/blogs/kevin-grigorenko1/2023/03/20/lessons-from-the-field-27-avoiding-core-dump-trunc
