### ISSUE TITLE
Deprecate support for running xlinux on CentOS 6

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1037]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16532

**Overview:**
Support for running jdk8, jdk11 on CentOS 6 is deprecated. OpenJ9 will no longer test xlinux jdk11 on CentOS 6 after 0.36, and may stop testing jdk8 in the future. When CRIU is enabled, it's not supported on CentOS 6 and testing can no longer run on this OS (without doing extra work to support this). Given CentOS 6 is end of life since November 30th, 2020, it's easier to deprecate support than to reconfigure the tests.

@tajila @llxia fyi

**Release target:**
OpenJ9 0.36 for deprecation, following releases will not be tested on CentOS 6.

**Applies to the following JDK versions:**
Java 8, 11

**Applies to the following platforms:**
xlinux

**Comment by doveye** [comment]
@pshipton if a customer has an issue on CentOS 6, presumably we will not be invetigating/fixing it (if we don't have the environments to test), so this is more of a removal (ie, saying we no longer support CentOS 6) rather than a deprecation (ie warning of future removal of support)?

**Comment by pshipton** [comment]
@doveye We still have the CentOS 6 environments at this time, they may be removed in the future.
