### ISSUE TITLE
The Java 19 release will be called 0.37

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1042]
**Issue or pull request number:**
N/A

**Overview:**
The Java 19 release will be called 0.37 rather than 0.36.1, since it's taking the latest code rather than fixes on the 0.36 release. The table of releases needs to be updated. https://eclipse-openj9.github.io/openj9-docs/openj9_support/

The plan ATM is to release jdk8, jdk17 as 0.36.0, and jdk11 as 0.36.1.

The 0.37 change impacts the Java 20 release. I expect the April release will remain as 0.38 and Java 20 will deliver afterwards as 0.39 (hopefully).

**Release target:**
0.36

**Applies to the following JDK versions:**
Java 19

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Please see the following image. Are the changes as per the requirements mentioned in the issue? 
<img width="731" alt="Screenshot 2023-01-30 at 6 39 10 PM" src="https://user-images.githubusercontent.com/98081349/215486823-4af901bc-ebbc-41d7-aed9-30da0a562922.png">

Few clarifications required:

1. You have mentioned that this is "the plan ATM", so does that mean I should not commit these changes till it is finalised and you give a go-ahead?
2. Does 0.36.1 have only one change, that is, release of JDK11? 
I will have to change the relevant sections of the 0.36.0 release notes and What's New topic as well to reflect this change.  Should I go ahead with that change or wait?

Thanks!

**Comment by pshipton** [comment]
We have the go ahead and can merge an update. If it doesn't work out, the 0.37 release may be dropped, but that is covered by note 1. Let's use a June date for Java 20. I have no idea yet what the date might be, but (a) we can refine it when doing the doc updates for April, and (b) if 0.39 / Java 20 does ship in July then we'd likely include all 8, 11, 17, 20 since July is the next quarterly update after April. 

> Does 0.36.1 have only one change, that is, release of JDK11?

Yes. Pls go ahead with the change.
