### ISSUE TITLE
Move AIX compiles to 7.2

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1043]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16581

**Overview:**
AIX compiles are moved from 7.1 to 7.2

**Release target:**
0.37

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
AIX

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - I will make the changes in the Supported environments topic. Few clarifications required:

- Under the Platform support section, can I delete the AIX 7.1 TL5 row from all the AIX related tables under all the OpenJDK binaries sections?
- Under the Build environments section, the operating system for the AIX POWER BE 64-bit platform has to be changed to AIX 7.2 TL4 for all JDK versions, isn't it? is there any related change to the compiler information for the platform? Is the compiler information same for all OpenJDK versions?

Thanks!

**Comment by pshipton** [comment]
>  can I delete the AIX 7.1 TL5 row

Yes

>  has to be changed to AIX 7.2 TL4 for all JDK versions

Pls change to TL5, the machines have the latest TL level.

>  Is the compiler information same for all OpenJDK versions?

Yes

**Comment by pshipton** [comment]
> is there any related change to the compiler information for the platform?

No, the compiler versions remain the same.

**Comment by pshipton** [comment]
> Is the compiler information same for all OpenJDK versions?

To clarify, the compiler versions remain the same. It's 7.2 TL5 for all versions.
