### ISSUE TITLE
Improvement to RHEL 6 support statement

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1044]
**Subject:**
https://eclipse-openj9.github.io/openj9-docs/openj9_support/

**Suggestion:**
For  CentOS 6.10 we say  "However, this support is deprecated and will be removed in a future release.". We should also add something like "Removing support also means the minimum glibc level (x) will be increased to 2.17."

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - what is the current minimum glibc version that will be increased to 2.17 after removing support?

**Comment by pshipton** [comment]
2.12

"Linux distributions that have a minimum glibc version 2.12 (x) or 2.17 (others)"
