### ISSUE TITLE
Support for Ubuntu 18.04 ends April 30, 2023

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1045]
**Issue or pull request number:**
N/A

**Overview:**
Support for Ubuntu 18.04 ends April 30, 2023, it needs to be removed from the list of supported platforms.

**Release target:**
0.38 (April release)

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
Linux platforms

**Comment by Sreekala-Gopakumar** [comment]
@doveye @pshipton - This issue can be closed. Fixed through https://github.com/eclipse-openj9/openj9-docs/pull/1060#issuecomment-1438856272
