### ISSUE TITLE
Document OpenSSL memory leak as a known limitation

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1047]
**Subject:**
https://github.com/eclipse-openj9/openj9/issues/16451
https://openj9.slack.com/archives/C01C8PL6319/p1675170015354169

**Suggestion:**
There is a known limitation that should be documented in the release notes.

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Is the following content correct?
<img width="899" alt="Screenshot 2023-02-02 at 8 21 54 PM" src="https://user-images.githubusercontent.com/98081349/216358476-624ac8b7-2185-4680-8073-5e01311e2b26.png">

1. Is it applicable to all levels of Java/OpenSSL?
2. Is it a known issue from 0.33.1 onwards?
3. Any workarounds? Can the following be considered as a workaround - "patch our production services to add a cron to weekly restart our app servers"?

**Comment by pshipton** [comment]
> Is it applicable to all levels of Java/OpenSSL?

Afaik, since we believe it's a bug in how Semeru uses OpenSSL.

> Is it a known issue from 0.33.1 onwards?

Afaik it's always been an issue in any version of OpenJ9 using OpenSSL. It's probably limited to certain types of OpenSSL usage, but I don't have enough information to say which parts. Usage of OpenSSL is broken down into acceleration of multiple algorithms (i.e. CBC, RSA, GCM, etc.), as seen in https://www.eclipse.org/openj9/docs/djdknativecrypto/

> Any workarounds?

I suppose "restart the application on a regular basis" is a workaround. So is disabling use of OpenSSL, either in whole or in part (if somebody can figure out which part(s) contain the leaks). However disabling use of OpenSSL may have a big impact on performance.

> when using AWS Java Client libraries

I doubt the leak is restricted to using AWS, this is just one example that exposes the leak.
