### ISSUE TITLE
OpenJ9 adds limited support for the com.sun.management.TheadMXBean interface

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1056]
**Issue or pull request number:**
Implement methods in com.sun.management.ThreadMXBean

**Overview:**
OpenJ9 adds limited support for the com.sun.management.TheadMXBean interface. For jdk11+ this interface is in the jdk.management module. The pre-existing com.ibm.lang.management.ThreadMXBean interface now inherits from com.sun.management.TheadMXBean.

Some of the methods throw UnsupportedOperationException, but supporting the interface ensures code that uses com.sun.management.TheadMXBean can compile on Semeru builds.

**Release target:**
0.37

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
Hi Peter, Could you please provide a little more information?

- What is the benefit to the user by adding limited support for the com.sun.management.ThreadMXBean interface? What was happening before this? With this change is it solving any portability issues? Is it helpful for porting applications from hotspot to OpenJ9?

Thanks!

**Comment by pshipton** [comment]
There are two benefits that come to mind:
1) apps written using com.sun.management.ThreadMXBean will compile with an OpenJ9 build
2) apps that uses com.sun.management.ThreadMXBean APIs may run on OpenJ9

getThreadCpuTime(long[] ids) and getThreadUserTime(long[] ids) work as expected, isThreadAllocatedMemorySupported() returns false, and the other APIs, which are for thread allocated memory, throw UnsupportedOperationException which is allowed by the spec and apps should handle this.

**Comment by pshipton** [comment]
BTW I expect all we need here is a one liner in the What's New and release notes "Compatibility is added for the com.ibm.lang.management.ThreadMXBean interface.". Anyone affected should understand. Anything else we add is just bonus and probably not necessary.
