### ISSUE TITLE
tokenLabel support for SunPKCS11 configuration on Linux on Z

### ISSUE THREAD

**Issue by BobMDu** [eclipse-openj9/openj9-docs#1057]
**Issue or pull request number:**
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/547

**Overview:**
Allows the user to specific the token's label when configuring the SunPKCS11 provider.
Lets the user avoid having to check which slot the token is in order to configure with the slot number and continues supporting a feature offered by the IBMPKCS11Impl provider for Java 8. 

**Release target:**
0.37

**Applies to the following JDK versions:**
JDK 11 and later

**Applies to the following platforms:**
Linux on Z

**Comment by pshipton** [comment]
Are there any examples or existing doc for configuring the SunPKCS11 provider? Is there any old IBM doc for this? We should probably give an example of how to set the tokenLabel.

**Comment by BobMDu** [comment]
We have an example [here on the z/OS SunPKCS11 Guide](https://public.dhe.ibm.com/software/Java/Java11/PKCS11/SunPKCS11Guide.html) that is linked from the [IBM Docs page](https://www.ibm.com/docs/en/semeru-runtime-ce-z/11?topic=guide-pkcs11).

![image](https://user-images.githubusercontent.com/25011446/219136621-2ae4dc17-87ab-47d2-8555-c52cf64b376c.png)

Since this is a feature brought forward from IBMPKCS11Impl, [the Config Documentation for it](https://www.ibm.com/docs/en/sdk-java-technology/8?topic=devices-configuration-file) also has some information about `tokenLabel`.

**Comment by Sreekala-Gopakumar** [comment]
Hi Peter, I couldn't find any topic related to PKSC11 in the existing OpenJ9 document. 

- Do we need a separate topic or a section in an existing topic? I will need the required content for that.
- How is this addition useful for the OpenJ9 users? Is this something they need to know? A little more clarity will be useful.
Thanks!

**Comment by doveye** [comment]
I'm wondering whether this should be documented in the OpenJ9 docs at all, or whether it should be documented in relation to Semeru like the FIPS guide that's linked to from https://www.ibm.com/support/pages/node/6612693.

**Comment by pshipton** [comment]
Technically it's not related to OpenJ9 itself, it's a change in the ibmruntimes OpenJDK extensions, but it does affect all builds of the OpenJDK extensions + OpenJ9. We've documented other things such as OpenSSL in the OpenJ9 docs, which are similarly not related to OpenJ9 itself.

@BobMDu can you pls take a stab at answering https://github.com/eclipse-openj9/openj9-docs/issues/1057#issuecomment-1437151429 - "How is this addition useful for the OpenJ9 users? Is this something they need to know? A little more clarity will be useful."

**Comment by pshipton** [comment]
It may also be worth noting that other security related changes are in the works and will be delivered in future releases. This is just the first.

**Comment by BobMDu** [comment]
@pshipton @Sreekala-Gopakumar It's useful for anyone that is transitioning from IBM Java 8 SDK to IBM Semeru SDK versions. tokenLabel is a feature brought forward from the IBMPKCS11Impl provider used in Java 8.

It's also useful in general for anyone using OpenJDK and PKCS11, and has tokens that are constantly changing: if tokens are created or removed, slot numbers can change and specifying by label avoids having to find the new slot number to configure with each time. 

It isn't something that users have to know though; they can still configure the provider using the slot number following Oracle's documentation.

**Comment by doveye** [comment]
> It may also be worth noting that other security related changes are in the works and will be delivered in future releases. This is just the first.

This is useful info, thanks Peter. So maybe we should have a new "Security" section (after "Configuring", or perhaps before "Diagnostics"). We could move much of the OpenSSL content from https://www.eclipse.org/openj9/docs/introduction/#cryptographic-operations to a dedicated OpenSSL topic in this new Security section, leaving behind an intro with a link, which would be more consistent with the rest of the intro topic. Then we could have another topic (or multiple topics) to cover the other security changes. Maybe "Enhancements to OpenJDK security" would be an appropriate title, at least for now with this one change.
