### ISSUE TITLE
 Add zOS default settings under -Xlp:objectheap pagesize section

### ISSUE THREAD

**Issue by joransiu** [eclipse-openj9/openj9-docs#1064]
**Subject:** 
*E.g. component, feature, existing page*

The current documentation for [-Xlp:objectheap](https://www.eclipse.org/openj9/docs/xlpobjectheap) can be enhanced to include the z/OS default page size in the `pagesize` section.   Specifically, a z/OS entry in the following text would be useful.

> Default page sizes
> 
>     On Linux systems, the default size for the object heap depends on the architecture:
> 
>         Linux on x86 and AMD64/EM64T systems: 2 MB large pages
>         Linux on IBM Z®: 1 MB large pages
>         On other architectures, the VM uses the default operating system page size.
> 
>     On macOS, the default page size is 4 KB.

Note, the z/OS default of 1MB pageable is mentioned in the subsequent `pageable|nonpageable` section:

> On z/OS systems, defines the type of memory to allocate for the Java object heap.
> 1 MB pageable large pages, when available, are the default size for the object heap.

**Suggestion:** I think it'll be good to either cross-reference, or just mention the z/OS default in both sections to avoid confusion.

**Comment by Sreekala-Gopakumar** [comment]
@joransiu - Under which release is this issue logged? Thanks!

**Comment by doveye** [comment]
@Sreekala-Gopakumar as it's a doc enhancement, it's not specific to a release. It can be done for 0.37 if there's time.
