### ISSUE TITLE
Documentation for -XX:[+|-]HandleSIGUSR2 

### ISSUE THREAD

**Issue by babsingh** [eclipse-openj9/openj9-docs#1077]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/16974

**Overview:**
-XX:-HandleSIGUSR2 will allow a user to install a signal handler for
SIGUSR2 without relying upon signal handler chaining (jsig).

**Release target:**
Eclipse OpenJ9 0.38.0

**Applies to the following JDK versions:**
 8 and later

**Applies to the following platforms:**
All platforms except Windows.

**For new command line options:**
See draft PR https://github.com/eclipse-openj9/openj9-docs/pull/1076 for details.

**Comment by Sreekala-Gopakumar** [comment]
> **Issue or pull request number:** [eclipse-openj9/openj9#16974](https://github.com/eclipse-openj9/openj9/pull/16974)
> 
> **Overview:** -XX:-HandleSIGUSR2 will allow a user to install a signal handler for SIGUSR2 without relying upon signal handler chaining (jsig).
> 
> **Release target:** Eclipse OpenJ9 0.38.0
> 
> **Applies to the following JDK versions:** 8 and later
> 
> **Applies to the following platforms:** All platforms except Windows.
> 
> **For new command line options:** See draft PR #1076 for details.

What do you mean by "-XX:-HandleSIGUSR2 will allow a user to install a signal handler for SIGUSR2 without relying upon signal handler chaining (jsig)"? This option is used only for disabling the VM from handling the signal `SIGUSR2`, isn't it? So, how can a user install a signal handler for SIGUSR2?

In the following sentence, does the second sentence mean that if a user does not install a signal handler, then this signal is handled by the default operating system handler?

"When the option is disabled, the VM does not handle the signal `SIGUSR2`. Generally, this signal is handled by the default operating system handler."
