### ISSUE TITLE
0.38 doesn't support Java 19

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1086]
**Page containing the error:**

https://eclipse-openj9.github.io/openj9-docs/openj9_support/

**Describe the error and the update needed:**

0.38 doesn't support Java 19

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - In this topic, I must edit the support for Java 19 in 0.37.0 as well, isn't it? 0.37.0 release doesn't support Java 19 as per https://github.com/eclipse-openj9/openj9/pull/17178

**Comment by pshipton** [comment]
0.37 only "supports" Java 19, although Java 19 is "out of support". :) 
We are providing out of support builds of Java 19 via 0.37.

**Comment by pshipton** [comment]
The previous comment is different from 0.38, because the 0.38 release stream don't contain all the code changes and fixes required to run Java 19.
