### ISSUE TITLE
CRIU Support Documentation Updates for 0.40

### ISSUE THREAD

**Issue by dsouzai** [eclipse-openj9/openj9-docs#1092]
**Overview:**
* Describe JITServer behaviour changes wrt to CRIU (https://github.com/eclipse-openj9/openj9/pull/17205)

**Release target:**
Eclipse OpenJ9 0.40.0*

**Applies to the following JDK versions:**
JDKs that implement OpenJ9 CRIU Support

**Applies to the following platforms:**
Linux only on x96, P, Z

**Comment by Sreekala-Gopakumar** [comment]
@dsouzai - Any further updates in this issue? Thanks!

**Comment by dsouzai** [comment]
No other updates, this is the only change from the JIT side for 0.40. @JasonFengJ9 may have other updates though for the VM.

**Comment by Sreekala-Gopakumar** [comment]
> There are a couple of VM updates in progress, one is [CRIU throws JVMCRIUException in single threaded mode if parks no timeout](https://github.com/eclipse-openj9/openj9/pull/17573), the other one is to adjust `VirtualThread.DEFAULT_SCHEDULER.PARALLELISM` for carrier thread scheduling according to `Runtime.availableProcessors()`.
> Will provide details after the PR approval/merge.

Is this change approved and merged as yet (I can see that this PR is not closed)?

**Comment by JasonFengJ9** [comment]
> Is this change approved and merged as yet (I can see that this PR is not closed)?

Not yet, also opened 
* https://github.com/eclipse-openj9/openj9/pull/17618

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9  - The following issues seem more like API doc changes. So, I can skip these since I am documenting user docs?

https://github.com/eclipse-openj9/openj9/pull/17618 and https://github.com/eclipse-openj9/openj9/pull/17573

**Comment by JasonFengJ9** [comment]
* https://github.com/eclipse-openj9/openj9/pull/17618 
is not in the main branch yet.

* https://github.com/eclipse-openj9/openj9/pull/17573
is an internal implementation change, no user doc update is required.

> So, I can skip these since I am documenting user docs?

Right
