### ISSUE TITLE
Document new option -XX:codecachetotalMaxRAMPercentage=N

### ISSUE THREAD

**Issue by SajinaKandy** [eclipse-openj9/openj9-docs#1108]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/17425

**Overview:**
The option `-XX:codecachetotalMaxRAMPercentage=N` sets a maximum limit for the total memory allocated by the JVM for code caches, limit expressed as a percentage of the available physical memory.
The value `N` needs to be a number between 1 and 100 (fractional numbers are allowed).
For example, with the option  `-XX:codecachetotalMaxRAMPercentage=30` the JVM is not allowed to use more than 30% of the available physical memory for its internal code caches.
Default: The default value for this option is 25, which means 25% of the available physical memory.

Note that this option does not indicate a prescribed total code cache value, but rather sets a maximum limit. In environments with low memory availability this option can shrink the default total code cache value (the default is set to 256 MB for 64-bit systems and 64 MB for 31/32-bit  systems), while in environments with plenty of memory it will have no effect. If you want to increase the total code cache value use the `-XX:codecachetotal=size` or the `-Xcodecachetotal=size` options.

Note that you can specify a prescribed total code cache value with  `-XX:codecachetotal=size` or  `-Xcodecachetotal=size` options. When that happens, the limit set with  `-XX:codecachetotalMaxRAMPercentage=N` is ignored.

**Release target:**
Eclipse OpenJ9 0.40.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms 

**For new command line options:**

- XX:codecachetotalMaxRAMPercentage=N
- Values are set:
	- Units for setting: %
	- Range: 1-100, can be fractional values.
	- Default value: 25
- Purpose: Set the maximum limit for the JVM's total code cache memory, limit expressed as a percentage of the physical memory available to the JVM. The intent is to prevent the JVM from using too much memory for its code cache in environments with low physical memory availability..
- Restrictions: If -XX:codecachetotal=<size> or -Xcodecachetotal<size> is specified, then -XX:codecachetotalMaxRAMPercentage=N is ignored. 
            - The specified percentage of the physical available memory is used only if the calculated total cache value is less than the default total code cache value set for the platform.

**Comment by SajinaKandy** [comment]
@mpirvu Attn.

**Comment by mpirvu** [comment]
Attn: @Sreekala-Gopakumar
