### ISSUE TITLE
Documentation for -XX:ContinuationCache:t1=<U_32>,t2=<U_32>

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse-openj9/openj9-docs#1124]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/17643

**Overview:**
`-XX:ContinuationCache:t1=<U_32>,t2=<U_32>` option allow manual setting of Continuation tier 1/2 cache size to optimize for Virtual Thread performance.

**Release target:**
Eclipse OpenJ9 0.41.0

**Applies to the following JDK versions:**
Java 21 and later

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: *`-XX:ContinuationCache:t1=<U_32>,t2=<U_32>`*
	- Units for setting: *integer*
	- Range: *0 - 2^32*
	- Default value: *N/A*

**Comment by fengxue-IS** [comment]
@Sreekala-Gopakumar let me know if you have any further questions.
> * What is the Continuation tier? What is 1/2 cache size?

OpenJ9's Continuation cache is implemented in 2 tiers, with tier 1 being thread local, tier 2 being shared globally.
1/2 cache size is short for tier1 and tier2 cache size
> * Which cache are we talking about here?

Continuation cache is an optimization where JVM recycles the native continuation structure allocated for virtual thread to improve virtual thread creation performance.
> * What do the parameters t1=<U_32> and t2=<U_32> mean?

`<U_32>` refers to the size limit, were the number of cache entries in tier 1 and tier 2 must be between 0 ~ U32_MAX
> * How is the setting set to automatic if this option allows manual setting?

The default value of the cache is 1 for tier 1, and number of processor x 2 for tier 2 (ie. `t1=1,t2=<processor*2>`)

Thanks

**Comment by Sreekala-Gopakumar** [comment]
What do you mean by "Continuation cache is an optimisation"? So it is not a cache like JIT or AOT cache?
Could you please elaborate on "native continuation structure allocated"? Is it different from memory?

Thanks for your input!

**Comment by fengxue-IS** [comment]
> What do you mean by "Continuation cache is an optimisation"? So it is not a cache like JIT or AOT cache? Could you please elaborate on "native continuation structure allocated"? Is it different from memory?

A continuation is the underlying structure that holds the task/state of a virtualthread. when a Continuation is being executed, VM allocates native memory for it to hold internal data structure. Continuation cache refers to when the execution completes, instead of freeing the allocated memory, VM would store such allocated memory in a cache and when a new continuation need to execute, instead of allocating new memory, it can directly use the cached structure.

In Java, object allocated are on heap and managed by GC, "native continuation structure" is internal to the VM (similar to JIT code cache) and not visible to user / GC

**Comment by fengxue-IS** [comment]
What I meant by "Continuation cache is an optimization" is that such cache is optional from functionality perspective. unlike JIT/AOT cache which must exist if you want to use JIT/AOT feature, specifying `-XX:ContinuationCache:t1=0,t2=0` doesn't affect its usability, only performance may be impacted

**Comment by Sreekala-Gopakumar** [comment]
"native continuation structure" is internal to the VM (similar to JIT code cache) and not visible to user / GC" - Could you please explain how this option is useful to the user? 

In the existing documents, we have not discussed the continuation cache or continuation structure anywhere. So I was wondering about the relevance of this option to the user. Whether this cache and the native continuation structure needs a mention in other topics as well?

Could you also explain the size limit? Is high limit good or a low limit?

Thanks!

**Comment by fengxue-IS** [comment]
> "native continuation structure" is internal to the VM (similar to JIT code cache) and not visible to user / GC" - Could you please explain how this option is useful to the user?

The default cache size is relatively conservative to avoid wasting memory while maintaining performance benefit. For large machines that could be launching 10000+ virtual thread, setting a larger cache size can help to improve performance.

In real use, the size of the cache is a trade off between allocation vs cache lookup. (ie. increasing the size of the cache will reduce number of allocation but at the same time cache lookup time may increase with the increase in cache size).

please note this is still WIP in terms of how caching works, future improvements in cache logic could change how the default value is set and/or size of cache to be changed during runtime.

**Comment by Sreekala-Gopakumar** [comment]
@fengxue-IS - Is the option name `-XX:ContinuationCache` and its syntax `-XX:ContinuationCache:t1=<U_32>,t2=<U_32>`?

**Comment by fengxue-IS** [comment]
> @fengxue-IS - Is the option name `-XX:ContinuationCache` and its syntax `-XX:ContinuationCache:t1=<U_32>,t2=<U_32>`?

yes
