### ISSUE TITLE
OpenSSL EC and XDH acceleration

### ISSUE THREAD

**Issue by KostasTsiounis** [eclipse-openj9/openj9-docs#1131]
**Issue or pull request number:**
*EC Key Agreement:*
- JDK8: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/572 - 0.33
- JDK11: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/532 - 0.33
- JDK17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/114 - 0.33
- JDK18: https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/59 - 0.33
- JDK19: https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/6 - 0.37
- and later

*EC Key Generation:*
- JDK8: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/671 - 0.40
- JDK11: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/650 - 0.40
- JDK17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/206 - 0.40
- JDK20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/42 - 0.39

*XDH Key Agreement and Generation:*
- JDK11: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/664 - 0.40
- JDK17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/219 - 0.40
- JDK20: https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/55 - 0.40

**Overview:**
Acceleration is added for EC Key Agreement and Generation, as well as for XDH Key Agreement and Generation

**Release target:**
- EC Key Agreement: 0.33
- EC Key Generation: 0.39
- XDH Key Agreement and Generation: 0.40

**Applies to the following JDK versions:**
- EC Key Agreement and Generation: All JDK versions
- XDH Key Agreement and Generation: 11 onwards (not 8)

**Applies to the following OpenSSL versions:**
- EC Key Agreement and Generation: All OpenSSL versions
- XDH Key Agreement and Generation: 1.1.1 onwards

**Applies to the following platforms:**
All platforms

**For new command line options:**
All of the following flags are enabled by default.
- `jdk.nativeEC`: system property that controls EC Key Agreement individually, similarly to the other algorithms.
- `jdk.nativeECKeyGen`: system property that controls EC Key Generation individually, similarly to the other algorithms.
- `jdk.nativeXDHKeyAgreement`: system property that controls XDH Key Agreement individually, similarly to the other algorithms.
- `jdk.nativeXDHKeyGen`: system property that controls XDH Key Generation individually, similarly to the other algorithms.

All flags can be set to equal `true` or `false`.

The `XDH` flags are not available in Java 8.

**Comment by Sreekala-Gopakumar** [comment]
Is this change expected to go in 0.40.0 release? I can see that changes are expected in older releases going back to 0.33.0 release. What is the expectation here? Thanks!

@pshipton - For your input as well. Thanks!

**Comment by pshipton** [comment]
@Sreekala-Gopakumar yes the changes are in 0.40. EC Key Agreement is in 0.33 and later, we missed updating the doc. EC Key Generation is in 0.39 for Java 20. The expectation is that we update the doc to include the options, retroactively updating What's New for the appropriate versions.
