### ISSUE TITLE
Documentation for -XX:[+|-]EnableDynamicAgentLoading

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9-docs#1140]
**Issue or pull request number:**
* https://github.com/eclipse-openj9/openj9/pull/17215
* https://github.com/eclipse-openj9/openj9/pull/17932
* https://github.com/eclipse-openj9/openj9/pull/17990

**Overview:**
For Java 8 and later, the dynamic loading of JVM TI agents is enabled by default unless `-XX:-EnableDynamicAgentLoading` is specified.

For Java 21 and later, the following warnings are issued when an agent is loaded dynamically into a running VM after startup without specifying the -XX:+EnableDynamicAgentLoading option and the same agent wasn't loaded before:

_WARNING: A {Java,JVM TI} agent has been loaded dynamically (file:/u/bob/agent.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release_

For `AIX` platform that can't detect if an agent library was previously loaded, the warnings will be issued when an agent is loaded dynamically through Attach API `VirtualMachine.loadAgentLibrary(agent)` even if the agent was loaded via the command line `-agentpath:/Absolute/Path/to/agentLibrary` at startup.

**Release target:**
Eclipse OpenJ9 0.41.0

**Applies to the following JDK versions:**
`-XX:[+|-]EnableDynamicAgentLoading` - 8 and later
Issuing the warning message - 21 and later

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: *e.g. -XX:[+|-]EnableDynamicAgentLoading*

**Comment by pshipton** [comment]
We should also mention the new jcmd supported command JVMTI.agent_load, at least in the release notes.

**Comment by JasonFengJ9** [comment]
`0.41.md` is not available yet.
Probably no need to update https://eclipse.dev/openj9/docs/tool_jcmd/ which doesn't show the diagnostic command details, only examples.

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9 - What was the reason for introducing this new option? What was going wrong in the absence of this option?

What is the default setting for this option? The following line was not clear

> For Java 8 and later, the dynamic loading of JVM TI agents is enabled by default unless -XX:-EnableDynamicAgentLoading is specified.

The "unless -XX:-EnableDynamicAgentLoading is specified" is confusing. Is "dynamic loading of JVM TI agents" different from specifying `-XX:+EnableDynamicAgentLoading`? Or does this line mean that `-XX:+EnableDynamicAgentLoading` the default setting?

**Comment by JasonFengJ9** [comment]
> What was the reason for introducing this new option? What was going wrong in the absence of this option?

This is a [JEP 451](https://openjdk.org/jeps/451) requirement.

> What is the default setting for this option?

The current default setting is `-XX:+EnableDynamicAgentLoading`.

> Is "dynamic loading of JVM TI agents" different from specifying -XX:+EnableDynamicAgentLoading? Or does this line mean that -XX:+EnableDynamicAgentLoading the default setting?

Correct, `-XX:+EnableDynamicAgentLoading` is the default setting.

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9 - Is the following content correct? I also need a clarification regarding "...or the agent hasn't been loaded" as mentioned in the issue https://github.com/eclipse-openj9/openj9-docs/issues/1140#issue-1849775068. Does it mean that warnings are issued even if the `-XX:+EnableDynamicAgentLoading` option is specified but agents are not loaded at startup by using the command-line options?

"With the [Attach API](attachapi.md), your application can connect to a running VM and load an agent dynamically into that VM to run tasks. Some libraries misuse the Attach API to dynamically load an agent to run tasks without the approval of the application owner.

You can disable the dynamic loading of the agents into a VM after startup with the `-XX:-EnableDynamicAgentLoading` option. To enable dynamic loading explicitly, specify the `-XX:+EnableDynamicAgentLoading` option.

For Java&trade; 21 and later, the following warnings are issued when the agents are loaded dynamically into a running VM after startup without specifying the `-XX:+EnableDynamicAgentLoading` option or no agents are loaded at startup by using the [command-line options](interface_jvmti.md#overview):

```
WARNING: A {Java,JVM TI} agent has been loaded dynamically (file:/u/bob/agent.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
```"

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9 -  I also need a clarification regarding "...or the agent hasn't been loaded" as mentioned in the issue https://github.com/eclipse-openj9/openj9-docs/issues/1140#issue-1849775068. Does it mean that warnings are issued even if the `-XX:+EnableDynamicAgentLoading` option is specified but agents are not loaded at startup by using the command-line options?

**Comment by JasonFengJ9** [comment]
@Sreekala-Gopakumar I made some modifications according to a later PR
* https://github.com/eclipse-openj9/openj9/pull/17990 

> Is the following content correct?
> I also need a clarification regarding "...or the agent hasn't been loaded" as mentioned in the issue https://github.com/eclipse-openj9/openj9-docs/issues/1140#issue-1849775068. Does it mean that warnings are issued even if the -XX:+EnableDynamicAgentLoading option is specified but agents are not loaded at startup by using the command-line options?

Please match the updated issue description.

**Comment by Sreekala-Gopakumar** [comment]
Thanks, Jason!
