### ISSUE TITLE
Incorrect default cache size and suggestion for IPCSHMMPAGES configuration on z/OS

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9-docs#1141]
**Page containing the error:**
https://eclipse.dev/openj9/docs/configuring/#setting-resource-limits-zos

**Describe the error and the update needed:**

> By default, the VM attempts to create a 16 MB cache.

This is only true for Java 8. For Java 11 and up, the default cache size is 300 MB.

> The suggested minimum values for Java applications are shown in the following table:

In the table, the suggested value of IPCSHMMPAGES is 256, which allows a cache (non-persistent cache, which is the default cache type now on z/OS) with maximum size of 256 MB. It is smaller than the default cache size 300 MB. 

In the z/OS documentation https://www.ibm.com/docs/en/zos/2.5.0?topic=parameters-statements-bpxprmxx:
The default of IPCSHMMPAGES is 25600. We should change it to 25600 in the table.

**Comment by hangshao0** [comment]
FYI @joransiu @pshipton @r30shah

**Comment by pshipton** [comment]
@Sreekala-Gopakumar once this is updated we can add to the fix to the 0.40 branch and re-publish.
