### ISSUE TITLE
Changes to the behaviour of -Xshareclasses:readonly with JITServer AOT cache

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9-docs#1145]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/17945

**Overview:**
The `-Xshareclasses:readonly` option is now ignored under the following conditions:

1. The JITServer AOT cache feature is enabled, and the JVM is a client.
2. The JVM is running in a container.
3. AOT compilation is enabled.
4. The SCC is persistent.

Instead of applying that option, we instead create a temporary top SCC layer that the JITServer AOT cache can use to store a small amount of metadata that it needs to function. This allows the JITServer AOT cache to be used while keeping the existing layers unmodified.

**Release target:**
Eclipse OpenJ9 0.41.0

**Applies to the following JDK versions:**
All JDKs

**Applies to the following platforms:**
All platforms that support JITServer.

**Comment by cjjdespres** [comment]
@mpirvu @hangshao0. It's possible that the detailed description of this behaviour should be included somewhere in the JITServer AOT cache documentation, with a link to the description in the `-Xshareclasses:readonly` documentation.

**Comment by Sreekala-Gopakumar** [comment]
> @mpirvu @hangshao0. It's possible that the detailed description of this behaviour should be included somewhere in the JITServer AOT cache documentation, with a link to the description in the `-Xshareclasses:readonly` documentation.

@cjjdespres - Any more detailed information of this behaviour that needs to be added in the JITServer AOT cache documentation? If yes, could you please provide the same? Thanks!

**Comment by cjjdespres** [comment]
No, there's nothing more that I can think of. I just meant that the changes in the overview could be described somewhere in the JITServer AOT cache section of `jitserver_tuning`, and then there could be a sentence in the `-Xshareclasses:readonly` documentation mentioning that it's ignored under certain circumstances when JITServer AOT caching is enabled, linking to the more detailed description.

**Comment by Sreekala-Gopakumar** [comment]
>The SCC is persistent.

In this are we referring to the ` -Xshareclasses:persistent` option? 
Does the `-XX:+JITServerAOTCachePersistence` option play any role in this?

**Comment by Sreekala-Gopakumar** [comment]
Could you also explain why the behaviour of the -Xshareclasses:readonly option with JITServer AOT cache had to change? What was going wrong with this option? Thanks!

**Comment by Sreekala-Gopakumar** [comment]
@cjjdespres - I saw some new options in https://github.com/eclipse-openj9/openj9/pull/17945

- -XX:+JITServerAOTCacheDelayMethodRelocation
- -XX:[+|-]JITServerAOTCacheUseTemporaryLayer

Shouldn't we document these options as well?

Thanks!

**Comment by cjjdespres** [comment]
> In this are we referring to the  -Xshareclasses:persistent option?

Yes. This is unrelated to `-XX:+JITServerAOTCachePersistence`.

> Could you also explain why the behaviour of the -Xshareclasses:readonly option with JITServer AOT cache had to change? What was going wrong when this option was used? Thanks!

Before, if `-Xshareclasses:readonly` and the JITServer AOT cache were both enabled at the same time at a JITServer client, the client would be unable to use the JITServer AOT cache at all because the client couldn't use the cache for storing data that the JITServer AOT cache needs to have stored in order to function. The `-Xshareclasses:readonly` option would effectively cancel out the `-XX:+JITServerUseAOTCache` option. The new behaviour allows  `-Xshareclasses:readonly` and the JITServer AOT cache to be used together in more situations, and not have one cancel the other out.

> Shouldn't we document these options as well?

I think these were intended to be internal options that would revert some of the changes made in the PR in case things went wrong, and so don't need to be called out in the documentation. I think @mpirvu can confirm.
