### ISSUE TITLE
Ensure System.gc() triggers a GC and runs finalization

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1161]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/18044

**Overview:**
The JCL code expects that when System.GC() is called a GC occurs and finalizable objects are finalized. Historically, J9 has never provided this guarantee. We have often had to modify tests to ensure a GC is triggered at the appropriate time. Increasingly, we are finding that more and more tests rely on this behaviour, and most importantly, core JCL code now relies on this behaviour. This PR ensures that a call to System.gc() triggers a GC and runs finalization.

**Release target:**
0.42 (jdk21) and 0.43

**Applies to the following JDK versions:**
All versions

**Applies to the following platforms:**
All platforms

**Comment by pshipton** [comment]
@tajila @dmitripivkine

**Comment by dmitripivkine** [comment]
Old behaviour:
- If System.GC() is called during active GC cycle (Concurrent Marking has been kicked off already), this call completes active GC cycle by performing Stop The World GC. As a result some objects (dead de facto at the moment of call) might be not collected due recognition them alive earlier in this GC cycle. In the cases GC behaviour to collect particular object is tested single call of System.GC() might be not sufficient. So, calling it twice is a solution.

New behaviour:
 -  System.GC() call triggers GC execution twice internally. Also it triggers RunFinalization to complete handling of the objects in Finalization queues. So, explicit System.GC() call twice is not necessary any more.

**Comment by Sreekala-Gopakumar** [comment]
Is this change applicable only for JDK 21  or is it applicable for JDK 21 and later versions?

**Comment by pshipton** [comment]
It's applicable to all versions, jdk8+.

**Comment by Sreekala-Gopakumar** [comment]
> It's applicable to all versions, jdk8+.

ok. I got confused by jdk 21 in the Release target. Thanks!
