### ISSUE TITLE
OpenSSL v3 is supported on all platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1171]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/13686

**Overview:**
OpenSSL v3 is supported on all platforms, where before it was only supported on Linux. v3 is included on Windows/Mac instead of 1.1.1.

**Release target:**
Eclipse OpenJ9 0.41

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Based on this issue, is the following still valid?

>On Linux and AIX&reg; operating systems, the OpenSSL 1.0.x or 1.1.x library is expected to be found on the system path. If you use a package manager to install OpenSSL, the system path will be updated automatically. On other operating systems, the OpenSSL 1.1.x library is typically bundled. Later levels of some Linux operating systems might bundle OpenSSL 3.0.x.

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Here, does v3 mean OpenSSL 3.0.x? Thanks!

**Comment by pshipton** [comment]
I don't think it's restricted to 3.0, it could be any 3.x version. We happen to be bundling 3.0.x for this release but may bundle a later version in the future.

**Comment by pshipton** [comment]
On all platforms the search order is 3, 1.1, 1.0. Linux has done this for a while, but it's new in this release for the other platforms. 

Windows/Mac are bundling 3.0.x for this release. Some versions of Linux and AIX might bundle OpenSSL 3, or you might have the option to install OpenSSL 3 via the package manager.

**Comment by Sreekala-Gopakumar** [comment]
> I don't think it's restricted to 3.0, it could be any 3.x version. We happen to be bundling 3.0.x for this release but may bundle a later version in the future.

So, I can say OpenSSL 3.x is now supported on all operating systems? Thanks!

**Comment by pshipton** [comment]
> So, I can say OpenSSL 3.x is now supported on all operating systems?

Yes.
