### ISSUE TITLE
jextract is removed from Java 21 and later

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1183]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/18193

**Overview:**
jextract has been deprecated since 0.26. The jextract executable is removed from Java 21 and later. jpackcore has been available in builds from 0.26 and should be used instead.
https://eclipse.dev/openj9/docs/tool_jextract/#dump-extractor-jpackcore

**Release target:**
Eclipse OpenJ9 0.42

**Applies to the following JDK versions:**
Java 21 and later

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Should I delete the note "This tool replaces jextract, which is deprecated in Eclipse OpenJ9™ version 0.26.0." Is that the expected doc change? 

Or should I retain that note and add another note with Java 21 and later tag - "The jextract tool is removed from Java 21 and later."
