### ISSUE TITLE
CRIU Support

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9-docs#1198]
**Subject:**
Existing docs do not indicate that CRIU is only support on ubi8 and 9 container images.

**Suggestion:**
In https://www.ibm.com/docs/en/sdk-java-technology/8?topic=criu-support add another bullet point to indicate which container images have support

**Comment by Sreekala-Gopakumar** [comment]
@tajila - Can we write "CRIU is supported only on RHEL 8 and RHEL 9 Universal Base Images (UBI)." ?

Thanks!

**Comment by tajila** [comment]
Techanically the name is "Red Hat Universal Base Images". However, UBI is the known shorthand for this.

So Im not sure the "RHEL" part is accurate.
