### ISSUE TITLE
Ignore "allow" and "disallow" set in java.security.manager system property

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1212]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/18402

**Overview:**
For compatibility with JDK17 and later.
See https://github.com/eclipse-openj9/openj9/issues/18401

**Release target:**
0.41

**Applies to the following JDK versions:**
JDK8 and JDK11

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
Is the following correct:

> If you enable the `SecurityManager` at runtime by using the `System.setSecurityManager` system property, you must specify the `allow` token option from OpenJDK version 18 onwards. To disable the `SecurityManager`, specify the `disallow` option. If an application is designed to run on multiple OpenJDKs, the same command line is used across multiple versions of the OpenJDK. OpenJDK versions prior to version 12 ignore the `allow` and `disallow` options if specified.

Some clarifications required:
- Is `System.setSecurityManager` a system property?
- Where does `java.security.manager`system property come into the picture?

**Comment by pshipton** [comment]
> Is the following correct

Not exactly. Here is a rewrite.

If you enable the SecurityManager at runtime by calling the System.setSecurityManager() API, you must set the `-Djava.security.manager=allow` option from OpenJDK version 18 onwards. To disable setting the SecurityManager, specify the `-Djava.security.manager=disallow` option. If an application is designed to run on multiple OpenJDK versions, the same command line may be used across multiple versions. OpenJDK versions prior to version 12 now ignore the allow and disallow keywords if specified.


> Is System.setSecurityManager a system property?

No. `java.security.manager` is the system property. i.e. you can set `-Djava.security.manager=allow` or `-Djava.security.manager=disallow`.

**Comment by pshipton** [comment]
FYI, historically the `java.security.manager` system property is set to a class name. Example,
`-Djava.security.manager=my.security.Manager`. This causes the equivalent of the following code to be run during JVM startup.
```
my.security.Manager manager = new my.security.Manager();
System.setSecurityManager(manager);
```
