### ISSUE TITLE
Document new -XX:Compatibility=elasticsearch option

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9-docs#1213]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/18265
https://github.com/eclipse-openj9/openj9/pull/18387

**Overview:**
*A new option, `-XX:Compatibility=elasticsearch` was added to allow using OpenJ9 with ElasticSearch.*

**Release target:**
*Eclipse OpenJ9 0.43.0*

**Applies to the following JDK versions:**
*All JDK versions (although ElasticSearch required Java 17+).*

**Applies to the following platforms:**
*All platforms*

**For new command line options:**

- Option name and syntax: *-XX:Compatibility=elasticsearch*
- Purpose: Allow using OpenJ9 with ElasticSearch.

**Comment by Sreekala-Gopakumar** [comment]
@keithc-ca - Is the following content correct? Could you please check and let me know the changes that are required. Thanks!

# -XX:Compatibility

This option enables the compatibility mode that the OpenJDK can run in to support applications that require specific capabilities. For example, support for applications that rely on vendor-specific command line arguments or to make available unspecified APIs.

## Syntax

        -XX:Compatibility=<mode>
        
Where, `<mode>` is the application for which the compatibility mode is provided. The `<mode>` is case-insensitive.

In release 0.43.0, the compatibility mode is provided for the Elasticsearch application only.

        -XX:Compatibility=Elasticsearch

If the `-XX:Compatibility` option is specified more than once, or with a mode other than "Elasticsearch" (not case-sensitive), the VM fails to start.

Although this option is available in all OpenJDK versions, but the Elasticsearch application requires OpenJDK version 17 or later.

## Explanation

The Elasticsearch application was facing incompatibility issues when running on OpenJ9 and required many workarounds. With the `Elasticsearch` compatibility mode, OpenJ9 accepts and supports HotSpot-specific options or APIs that enhance compatibility to run the Elasticsearch application.

**Comment by keithc-ca** [comment]
That looks good. The only suggestion I have is to replace "enables the compatibility mode" with "enables a compatibility mode" in the first sentence. The option structure allows for other modes although at most one can be specified.

**Comment by pshipton** [comment]
We should use "OpenJ9" rather than "OpenJDK" in "that the OpenJDK can run in".
i.e. "that OpenJ9 can run in".

The following shouldn't use both "Although" and "but", one of them should be removed.
"Although this option is available in all OpenJDK versions, but the Elasticsearch application requires OpenJDK version 17 or later."
