### ISSUE TITLE
Document new -XX:[+|-]CRIUSecProvider option for CRIU

### ISSUE THREAD

**Issue by WilburZjh** [eclipse-openj9/openj9-docs#1244]
**Issue or pull request number:**
*https://github.com/eclipse-openj9/openj9/pull/18354*

**Overview:**
*Option controls if we want to enable the CRIUSec provider or not.*

**Release target:**
*Eclipse OpenJ9 0.43.0, and Eclipse OpenJ9 0.42.0 for JDK21*

**Applies to the following JDK versions:**
*11 and later*

**Applies to the following platforms:**
*Linux*

**For new command line options:**

- Option name and syntax: *-XX:[+|-]CRIUSecProvider*
- If values are set:
	- Default value: *enabled*
- Purpose: Control whether to use the CRIUSec provider during checkpoint phrase or not

**Comment by Sreekala-Gopakumar** [comment]
> @WilburZjh -
> 
> * If this option is disabled, then what is the behaviour? Are all the existing security providers retained in the security provider list during the checkpoint phase? Following is the existing content in the document (https://eclipse.dev/openj9/docs/criusupport/)
> 
> > The CRIU technical preview introduces the CRIUSECProvider security provider, which provides the following limited set of security services: MessageDigest and SecureRandom. When you enable CRIU support, all existing security providers are removed from the security provider list during the checkpoint phase and CRIUSECProvider is added. When you restore the VM in the nonportable restore mode ([-XX:+CRIURestoreNonPortableMode](https://eclipse.dev/openj9/docs/xxcriurestorenonportablemode/)), CRIUSECProvider is removed from the security provider list and the previous security providers are added back again.
> 
> * If we disable this option, what is the impact on -XX:[+|-]CRIURestoreNonPortableMode? In the existing document, we have the following content:
> 
> > When you disable this option,
> > - `CRIUSECProvider` is the only security provider in both checkpoint and restore.
> 
> https://eclipse.dev/openj9/docs/xxcriurestorenonportablemode/
> 
> Thanks!

@WilburZjh @pshipton - Any update on this? Thanks!

**Comment by pshipton** [comment]
@jasonkatonica fyi

**Comment by WilburZjh** [comment]
> If this option is disabled, then what is the behaviour? Are all the existing security providers retained in the security provider list during the checkpoint phase? Following is the existing content in the document

If this option is disabled, for example,` java -XX:+EnableCRIUSupport -XX:-CRIUSecProvider`, we no longer make use of the CRIUSec provider during the checkpoint phase, and instead we use default JCE security providers loading to enable all security algorithms in an out of the box state. This can allow users to make use of any algorithm in the various providers available. 

There are a few use cases identified so far for this option and an [issue](https://github.com/eclipse-openj9/openj9/issues/18422) is opened for this option. When this option is disabled, it's users' responsibility to take in charge of correctly handling some CRIU specific concerns.

**Comment by WilburZjh** [comment]
> If we disable this option, what is the impact on -XX:[+|-]CRIURestoreNonPortableMode? In the existing document, we have the following content:

I think there is a conflict between `-XX:-CRIURestoreNonPortableMode` and `-XX:-CRIUSecProvider`. `-XX:-CRIUSecProvider` aims to remove the CRIUSec provider during the checkpoint phase, but the `-XX:-CRIURestoreNonPortableMode` aims to use the CRIUSec provider during the checkpoint phase, that means if they are using in together, the CRIUSec provider will be removed during the checkpoint phase, and the JCE security providers will be loaded during the restore phase. 
For example,
` java -XX:+EnableCRIUSupport -XX:-CRIUSecProvider` will use normal providers during checkpoint phase.
` java -XX:+EnableCRIUSupport -XX:-CRIURestoreNonPortableMode` will use CRIUSec provider during checkpoint phase and restore phase
` java -XX:+EnableCRIUSupport -XX:-CRIUSecProvider -XX:-CRIURestoreNonPortableMode` will use normal providers during checkpoint phase and restore phase
