### ISSUE TITLE
Creating RSA Private Keys with SunPKCS11 + Opencryptoki in Java 21

### ISSUE THREAD

**Issue by BobMDu** [eclipse-openj9/openj9-docs#1257]
**Subject:**
SunPKCS11 for Java 21 on Linux on Z

**Suggestion:**
After testing with the SunPKCS11 provider we've noticed that users must have at least Opencryptoki version 3.22 or higher in order to generate RSA Private Keys with the ICA, CCA and EP11 tokens that opencryptoki supports.

**Comment by Sreekala-Gopakumar** [comment]
@BobMDu - Could you please provide the following information as well (like we have in all our OpenJ9 issues - [#1057](https://github.com/eclipse-openj9/openj9-docs/issues/1057))

Issue or pull request number:


Overview:


Release target:


Applies to the following JDK versions:


Applies to the following platforms:

**Comment by jpfurminger** [comment]
3.21 or 3.22?

**Comment by BobMDu** [comment]
> After testing with the SunPKCS11 provider we've noticed that users must have at least Opencryptoki version 3.21 or higher in order to generate RSA Private Keys with the ICA, CCA and EP11 tokens that opencryptoki supports. 

@jpfurminger 3.21 as written in my initial comment.

**Comment by BobMDu** [comment]
@Sreekala-Gopakumar 

Issue or pull request number: N/A

Overview: Users must have at least Opencryptoki version 3.21 or higher in order to generate RSA Private Keys with the ICA, CCA and EP11 tokens that opencryptoki supports.

Release target: as far as i'm aware the most recent semeru release for Linux on s390x is version 21.0.1.0

Applies to the following JDK versions: Java 21

Applies to the following platforms: Linux on s390x
