### ISSUE TITLE
JDK21+ AIX prints a warning message for the same library previously loaded

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9-docs#1264]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/18845
https://github.com/eclipse-openj9/openj9/pull/17990

**Overview:**
If an agent library was previously loaded via the command line or AttachAPI dynamically in the AIX platform and a warning message was printed, another loading of the same library will print "WARNING: A JVM TI agent has been loaded dynamically" again.

See https://github.com/eclipse-openj9/openj9-docs/issues/1264#issuecomment-1917302309 for more details.

**Release target:**
*Eclipse OpenJ9 0.44* 

**Applies to the following JDK versions:**
*21 and later*

**Applies to the following platforms:**
*AIX*

**For new command line options:**

- Option name and syntax: *-XX:[+|-]EnableDynamicAgentLoading*

An agent library can be loaded via an existing command line option `-agentpath:`.
When `-XX:-EnableDynamicAgentLoading` is specified, there will be no agent dynamical loading allowed and no more than one warning message to be printed.
When `-XX:+EnableDynamicAgentLoading` is specified which is on by default, an agent library can be loaded dynamically via `jcmd` command `JVMTI.agent_load`.

A workaround to avoid multiple warning messages is to only load the same library once.

FYI @pshipton @tajila

**Comment by pshipton** [comment]
Is there any workaround? How does the command option option affect the behavior?

**Comment by JasonFengJ9** [comment]
> Is there any workaround? How does the command option option affect the behavior?

Added the following in the issue description:

_There are no new command line options. An agent library can be loaded via an existing command line option `-agentpath:` or `jcmd` command `JVMTI.agent_load`._

_A workaround to avoid multiple warning messages is to only load the same library once._

**Comment by pshipton** [comment]
JEP451 adds a command line option, -XX:[+/-]EnableDynamicAgentLoading. So with -XX:-EnableDynamicAgentLoading you can't load the library at all, and with -XX:+EnableDynamicAgentLoading you get a warning if the library is loaded more than once, is that correct?

**Comment by pshipton** [comment]
And the difference between AIX and other platforms is that on AIX you get the warning every time the duplicate library is loaded, and for other platforms you only the warning the first time a dup library is loaded, correct?

**Comment by pshipton** [comment]
Also, for OpenJ9 this isn't a change in behavior from the previous release? But now OpenJDK has fixed AIX to only show the warning the first time, and OpenJ9 will make that change in the next release.

**Comment by Sreekala-Gopakumar** [comment]
> Also, for OpenJ9 this isn't a change in behavior from the previous release? But now OpenJDK has fixed AIX to only show the warning the first time, and OpenJ9 will make that change in the next release.

So this means that now AIX systems can detect whether an agent was previously loaded or not if the agent was loaded through a platform-independent name or an absolute path to the platform-dependent library? 

Now, on AIX also if the `-XX:+EnableDynamicAgentLoading` option is set, warning will be displayed but unlike other platforms, multiple warnings instead of a single warning will be displayed if the library is loaded more than once?

> JEP451 adds a command line option, -XX:[+/-]EnableDynamicAgentLoading. So with -XX:-EnableDynamicAgentLoading you can't load the library at all, and with -XX:+EnableDynamicAgentLoading you get a warning if the library is loaded more than once (every time it's loaded), is that correct?

@pshipton @JasonFengJ9 - As per https://github.com/eclipse-openj9/openj9-docs/issues/1140, "For Java 21 and later, the warnings are issued when an agent is loaded dynamically into a running VM after startup **without** specifying the -XX:+EnableDynamicAgentLoading option and the same agent wasn't loaded before."
Also, in the existing content, we are saying "If the `-XX:+EnableDynamicAgentLoading` option is set, all agents that are dynamically loaded are considered as approved by the application owner, and therefore, no warnings are issued." Please see https://github.com/eclipse-openj9/openj9-docs/pull/1174#discussion_r1332969137 also.

**Comment by JasonFengJ9** [comment]
> So this means that now AIX systems can detect whether an agent was previously loaded or not if the agent was loaded through a platform-independent name or an absolute path to the platform-dependent library?

This hasn't happened yet until https://github.com/eclipse-openj9/openj9/pull/18881 is approved & merged.

> Now, on AIX also if the -XX:+EnableDynamicAgentLoading option is set, warning will be displayed but unlike other platforms, multiple warnings instead of a single warning will be displayed if the library is loaded more than once?

On AIX if the -XX:+EnableDynamicAgentLoading option is **NOT** set, the warning will be displayed but unlike other platforms, multiple warnings instead of a single warning will be displayed if the library is loaded more than once?

> This seems contrary to the following comment

>>So with -XX:-EnableDynamicAgentLoading you can't load the library at all, and with -XX:+EnableDynamicAgentLoading you get a warning if the library is loaded more than once (every time it's loaded), is that correct

Good catch. The existing context is correct instead:
_"If the -XX:+EnableDynamicAgentLoading option is set, all agents that are dynamically loaded are considered as approved by the application owner, and therefore, no warnings are issued."_

**Comment by Sreekala-Gopakumar** [comment]
>This hasn't happened yet until https://github.com/eclipse-openj9/openj9/pull/18881 is approved & merged.

So, should I be documenting this as of now or should I keep it ready and reviewed and it can be merged as and when it is approved? Because, I guess, the warnings will be displayed only if the AIX systems can detect whether an agent was previously loaded or not if the agent was loaded through a platform-independent name or an absolute path to the platform-dependent library?

**Comment by JasonFengJ9** [comment]
>> This hasn't happened yet until https://github.com/eclipse-openj9/openj9/pull/18881 is approved & merged.

> So, should I be documenting this as of now or should I keep it ready and reviewed and it can be merged as and when it is approved?

The PR won't be merged into `0.43`. This doc is for the `0.43` known issue.

**Comment by Sreekala-Gopakumar** [comment]
> > > This hasn't happened yet until [eclipse-openj9/openj9#18881](https://github.com/eclipse-openj9/openj9/pull/18881) is approved & merged.
> 
> > So, should I be documenting this as of now or should I keep it ready and reviewed and it can be merged as and when it is approved?
> 
> The PR won't be merged into `0.43`. This doc is for the `0.43` known issue.

Could you clarify what you meant by "This doc is for the `0.43` known issue." What issue is being fixed that needed update in the documentation? I mean, we already have in our documents that 
>AIX systems cannot detect whether an agent was previously loaded or not if the agent was loaded through a platform-independent name or an absolute path to the platform-dependent library. Therefore, on AIX systems, the warnings are issued when an agent is loaded dynamically through the Attach API (`VirtualMachine.loadAgentLibrary(agent)`) even if the same agent was loaded before through the command-line option (`-agentpath:/Absolute/Path/to/agentLibrary`) at startup.

**Comment by pshipton** [comment]
What changed is that in 21.0.2 the Hotspot behavior changed so that AIX doesn't have this problem any more, but OpenJ9 still has the issue with 21.0.2, but it will be resolved in 21.0.3.

**Comment by Sreekala-Gopakumar** [comment]
> What changed is that in 21.0.2 the Hotspot behavior changed so that AIX doesn't have this problem any more, but OpenJ9 still has the issue with 21.0.2, it will be resolved in 21.0.3.

So, what exact change is required in the following topic for release 0.43.0? https://eclipse.dev/openj9/docs/xxenabledynamicagentloading/

**Comment by pshipton** [comment]
Just add a note that the AIX problem will be fixed in the next release.

**Comment by pshipton** [comment]
Reopened and added to 0.44 milestone, to indicate the AIX problem has been resolved.
