### ISSUE TITLE
Ignore "allow" and "disallow" set in java.security.manager system property on jdk8

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1279]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/18900

**Overview:**
https://github.com/eclipse-openj9/openj9-docs/issues/1212 was supposed to affect jdk8, but it didn't. Now jdk8 is updated to ignore "allow" and "disallow" set in the java.security.manager system property.

**Release target:**
Eclipse OpenJ9 0.44

**Applies to the following JDK versions:**
8 only

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Based on the content we already have in What's new in version 0.41.0 (https://eclipse.dev/openj9/docs/version0.41/#change-in-behavior-of-the-djavasecuritymanager-system-property-for-openjdk-version-8-and-11), is there any further update that is required for this issue?

**Comment by pshipton** [comment]
The change in 0.41 only updated jdk11 and jdk8 is updated in 0.44

**Comment by pshipton** [comment]
We should update the 0.41 content to be correct. It should only state jdk11. Then add the jdk8 change for 0.44.
