### ISSUE TITLE
-XX:+CompactStrings is default since 0.41

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1282]
**Page containing the error:**

https://eclipse.dev/openj9/docs/cmdline_migration/

**Describe the error and the update needed:**

-XX:+CompactStrings is the default since 0.41 and no longer needs to be enabled for compatible behavior.

**Comment by Sreekala-Gopakumar** [comment]
You mean that I should add a note similar to what we have given in the table under Compatible options for -XX:[+|-]CompactStrings? - "Note: This option is enabled by default in OpenJ9 on Java 11 and later. In the earlier versions, this option is disabled by default."

Also, in this issue, you have specified that this is applicable to Java 8 as well. As per the issue that was raised in 0.41.0, it was applicable for Java 11 and later. https://github.com/eclipse-openj9/openj9-docs/issues/1160
This has to be changed?

Thanks!

**Comment by pshipton** [comment]
> You mean that I should add a note similar to what we have given in the table under Compatible options for -XX:[+|-]CompactStrings? - "Note: This option is enabled by default in OpenJ9 on Java 11 and later. In the earlier versions, this option is disabled by default."

No. The option can be removed from the "Creating compatible behavior" table. From 0.41 the default behavior is compatible for this option.

> Also, in this issue, you have specified that this is applicable to Java 8 as well. As per the issue that was raised in 0.41.0, it was applicable for Java 11 and later. https://github.com/eclipse-openj9/openj9-docs/issues/1160
This has to be changed?

I didn't mean to imply anything different about jdk8 in this issue. The CompactStrings option can be enabled on jdk8, but it's not enabled by default. Nor is it required to be enabled on jdk8 for compatible behavior with Hotspot since Hotspot doesn't support it on jdk8. Since the defaults for jdk8 and jdk11+ match Hotspot behavior, CompactStrings is not needed in the "Creating compatible behavior" table.
