### ISSUE TITLE
Document -XX:[+|-]ShowCodeDetailsInExceptionMessages

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9-docs#1284]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/8450
https://github.com/eclipse-openj9/openj9/pull/8495
https://github.com/eclipse-openj9/openj9/pull/10912
https://github.com/eclipse-openj9/openj9/pull/11183

**Overview:**
A new option, `-XX:{+|-}ShowCodeDetailsInExceptionMessages` was added to describe precisely which variable was `null` when a NullPointerException is thrown by the JVM.

**Release target:**
*Eclipse OpenJ9 0.21.0*

**Applies to the following JDK versions:**
*14 and later*

**Applies to the following platforms:**
*All platforms*

**For new command line options:**

- Option name and syntax: *-XX:[+|-]ShowCodeDetailsInExceptionMessages*
- Purpose: Improve the usability of NullPointerExceptions generated by the JVM
- This option is enabled by default for JDK 15+

**Comment by JasonFengJ9** [comment]
FYI @pshipton

**Comment by Sreekala-Gopakumar** [comment]
@JasonFengJ9  @pshipton - Is this option applicable for JDK 14 and later (as mentioned in the "Applies to the following JDK versions:"), or JDK 15 and later (as mentioned in "For new command line options:")?

Thanks!

**Comment by JasonFengJ9** [comment]
>  Is this option applicable for JDK 14 and later (as mentioned in the "Applies to the following JDK versions:"), or JDK 15 and later (as mentioned in "For new command line options:")?

@Sreekala-Gopakumar This option is applicable for JDK14+ but was disabled by default in JDK 14, and enabled since JDK 15.
