### ISSUE TITLE
Document -Xtgc:allocation

### ISSUE THREAD

**Issue by amicic** [eclipse-openj9/openj9-docs#1296]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19070

**Overview:**
-Xtgc:allocation has existed 'forever' but just recently (for 0.46) has been enhanced so it may be more useful for users to find thread specific allocation stats, hence more reasons to document it.

An attempt here: https://github.com/eclipse-openj9/openj9-docs/pull/1295

**Release target:**
Eclipse OpenJ9 0.46

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by pshipton** [comment]
Updated to use the template and fill it in.
