### ISSUE TITLE
Document changes to writing DDR extensions

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9-docs#1306]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19173

**Overview:**
The names used in DDR code to refer to fields of `J9BuildFlags` have changed - they now consistently use the names of macros appearing in `j9cfg.h` (e.g. `env_data64` must now be referred to as `J9VM_ENV_DATA64`).

**Release target:**
*Eclipse OpenJ9 0.44.0*

**Applies to the following JDK versions:**
All JDK versions.

**Applies to the following platforms:**
All platforms.

**Comment by Sreekala-Gopakumar** [comment]
@keithc-ca - The only topics that I can see where DDR is discussed is in the What's new topics for 0.9.0 (https://eclipse.dev/openj9/docs/version0.9/#direct-dump-reader-enabled-on-linux-and-windows)  and 0.17.0 (https://eclipse.dev/openj9/docs/version0.17/#direct-dump-reader-ddr-vm-restriction-removed) releases. 

In this case also, can I just provide this information in the What's new in version 0.44.0 topic? Thanks!

**Comment by pshipton** [comment]
This is fine with me. Are there any IBM topics that need to be updated? I don't believe all of the documentation was made open source and some is still with IBM.

**Comment by Sreekala-Gopakumar** [comment]
@keithc-ca @pshipton - What was the problem because of which this change had to be made? How has this change helped? Thanks!

**Comment by Sreekala-Gopakumar** [comment]
> This is fine with me. Are there any IBM topics that need to be updated? I don't believe all of the documentation was made open source and some is still with IBM.

I couldn't find any reference to this in the IBM topics.

**Comment by keithc-ca** [comment]
The change was made to reduce complexity and improve the uniformity of how DDR code makes use of flags relating to the configuration of the JVM that produced a given system dump. 

Mapping of flag names was inconsistent (see recent changes to [overrides-vm](https://github.com/eclipse-openj9/openj9/blob/master/runtime/ddr/overrides-vm)) and introducing uses of flags that were not previously used meant either extra complexity (see [ValueTypeHelper.java](https://github.com/eclipse-openj9/openj9/blame/master/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/ValueTypeHelper.java#L300) for an example of complexity that was previously needed) or accepting that some flag tests would not apply to all system dumps (because the name was different at different times).

Now, the names to be used are those that appear in C/C++ code, independent of the JVM that produced a system dump (whether it predated the recent changes or not, whether it used the Semeru build process or the legacy tools employed in IBM Java 8 builds).

**Comment by Sreekala-Gopakumar** [comment]
@keithc-ca - Could you please check the below content I am planning to add in the What's new topic for 0.44.0 release. I want to check whether it is technically correct. Thanks!

> The Direct Dump Reader (DDR) code refers to the fields of `J9BuildFlags` to read build flags in the system dump data. These flags are related to the configuration of the VM that produced a given system dump. When the `J9BuildFlags` was generated for each build, the raw name of the build flags was used in the DDR code rather than the `cname` that appears in `j9cfg.h` (derived from `j9cfg.h.ft`). Therefore, mapping of flag names was inconsistent. Introducing new flags meant either extra complexity or accepting that some flag tests would not apply to all system dumps (because the flag name was different at different times).

Now, the flag names that are used in the DDR code to refer to the fields of `J9BuildFlags` are changed. The flag names are those names that appear in C or C++ code, independent of the VM that produced a system dump. This change updates how `J9BuildFlags` is generated (both as Java source and as dynamically produced bytecode) so the `cname` can be used consistently. To reduce complexity and improve the uniformity of how the DDR code makes use of the flags, the code now consistently uses the names of macros appearing in `j9cfg.h`. For example, `env_data64` is now referred to as `J9VM_ENV_DATA64`.

**Comment by pshipton** [comment]
We should first mention that user's need to modify DDR extensions that made use of J9BuildFlags to use the new names. Following that is the explanation for why the change was made.

**Comment by keithc-ca** [comment]
Suggestions:
* "the raw name ... was" should be "the raw name may have been"
* the source file is `j9cfg.h.ftl` (with the final `l`)
* the meaning of "this change" will be unclear in the docs; perhaps refer to the pull request or refer to it as a "recent change"
* "the code now consistently uses" doesn't quite convey the message that authors of DDR extensions may need to update their code to adopt the new (consistent) names

**Comment by Sreekala-Gopakumar** [comment]
@keithc-ca - Is there any other simpler way to say "...**raw name** of the flag names"?

Also, are "extensions" same as the "names that are used in the DDR code to refer to the flags in the `J9BuildFlags`? Thanks!

**Comment by pshipton** [comment]
It seems we should be calling them plugins rather than extensions. I assume the `!plugins` command is what is used to load them.
The closest documentation I found is at https://eclipse.dev/openj9/docs/tool_jdmpview/, under `!j9help`, which states "The expert parameters are subject to change and not intended as a supported interface". However some users are aware of plugins and own some, so should be warning they might break if using J9BuildFlags.

```
!plugins help
plugins <subcmd>                DDR Plugin management commands
        reload                  Reload plugins for the current context
        showpath                        Displays the current plugin search path
        setpath <search path>           Sets the current plugin search path
        list                    Show the list of loaded plugins for the current context
```

**Comment by Sreekala-Gopakumar** [comment]
> It seems we should be calling them plugins rather than extensions. I assume the `!plugins` command is what is used to load them.
> 
> The closest documentation I found is at https://eclipse.dev/openj9/docs/tool_jdmpview/, under `!j9help`, which states "The expert parameters are subject to change and not intended as a supported interface". However some users are aware of plugins and own some, so should be warned they might break if using J9BuildFlags.
> 
> ```
> !plugins help
> plugins <subcmd>                DDR Plugin management commands
>         reload                  Reload plugins for the current context
>         showpath                        Displays the current plugin search path
>         setpath <search path>           Sets the current plugin search path
>         list                    Show the list of loaded plugins for the current context
> ```

So, should I change "extensions" to "plugins"? Also, is DDR code a "plugin" and does this "plugin" have the "names that are used in the DDR code to refer to the flags in the `J9BuildFlags`? Thanks!

**Comment by pshipton** [comment]
> should I change "extensions" to "plugins"?

yes

> is DDR code a "plugin" and does this "plugin" have the "names that are used in the DDR code to refer to the flags in the J9BuildFlags?

No. DDR is the Direct Dump Reader. It's used to implement the `jdmpview` utility, and provides many built in commands, as documented in https://eclipse.dev/openj9/docs/tool_jdmpview/. User's can extend it, adding their own commands, by writing plugins. These user plugins may contain code that reference the `J9BuildFlags`. This code may need to be updated.
