### ISSUE TITLE
Securing the Attach API enhancement - prevent a user from interfering the AttachAPI via file permission modification

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9-docs#1307]
**Subject:**
https://eclipse.dev/openj9/docs/attachapi/

**Suggestion:**

_In the default Attach API directory you can find certain files that start with an underscore _*, which are involved in synchronization. These files can be owned by any user but must have read and write permissions set. The files are empty and are automatically re-created if deleted._
is changed to
_In the default Attach API directory you can find certain files that start with an underscore _*, which are involved in synchronization. By default these files can be owned by any user but must have read and write permissions set. The files are empty and are automatically re-created if deleted. To prevent a user from interfering the AttachAPI via file permission modification, root can be set as the folder/files owner to protect the file permissions._

**Comment by pshipton** [comment]
@paulcheeseman fyi
