### ISSUE TITLE
Remove CentOS Stream 8 from list of supported platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1317]
**Subject:**
https://eclipse-openj9.github.io/openj9-docs/openj9_support/

**Suggestion:**
CentOS Stream 8 is EOL May 31, 2024 and so we need to remove it from the list of supported platforms.

**Comment by Sreekala-Gopakumar** [comment]
But, isn't the GA date for 0.44.0 release before May 31st? Then should we remove it now?
