### ISSUE TITLE
Clarify overridden GC hint value for -Xms case

### ISSUE THREAD

**Issue by amicic** [eclipse-openj9/openj9-docs#1319]
From:

https://eclipse.dev/openj9/docs/xxusegcstartuphints/

```When enabled, this option overrides any initial heap size that is specified on the command line, for example by using the [-Xms](https://eclipse.dev/openj9/docs/xms/) option.```

Suggestion:

The overridden value can only be larger than either default or explicitly set -Xms value. So, the above sentence would benefit from something like:

```When enabled, this option overrides any initial heap size that is specified on the command line, for example by using the [-Xms](https://eclipse.dev/openj9/docs/xms/) option, while still obeying (-Xms, -Xmx) limits.```

**Comment by Sreekala-Gopakumar** [comment]
@amicic - By "while still obeying (-Xms, -Xmx) limits", do you mean that the new value should be greater than -Xms set value and lesser than -Xmx set value?

**Comment by amicic** [comment]
> @amicic - By "while still obeying (-Xms, -Xmx) limits", do you mean that the new value should be greater than -Xms set value and lesser than -Xmx set value?

Correct
