### ISSUE TITLE
TheadMXBean.getTotalThreadAllocatedBytes is implemented

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1326]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19436/

**Overview:**
In 0.41 getThreadAllocatedBytes() was added, but getTotalThreadAllocatedBytes was never implemented and would throw UnsupportedOperationException. Now it is implemented. Also as of jdk8u422 (0.46), OpenJDK has backported getTotalThreadAllocatedBytes() to jdk8.

https://eclipse.dev/openj9/docs/version0.41/#support-added-for-the-comsunmanagementthreadmxbeangetthreadallocatedbytes-api

**Release target:**
0.46

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - What does `getTotalThreadAllocatedBytes` do? How is it different from `getThreadAllocatedBytes()`?

**Comment by pshipton** [comment]
getThreadAllocatedBytes is the allocated bytes for a single thread, getTotalThreadAllocatedBytes is the total for all threads.

**Comment by Sreekala-Gopakumar** [comment]
Is `getTotalThreadAllocatedBytes` a method or an API like `com.sun.management.ThreadMXBean.getTotalThreadAllocatedBytes()` API? Will it be correct to say that "Support added for the `com.sun.management.ThreadMXBean.getTotalThreadAllocatedBytes()` API"

**Comment by pshipton** [comment]
Yes, yes it is.

https://docs.oracle.com/en/java/javase/21/docs/api/jdk.management/com/sun/management/ThreadMXBean.html#getTotalThreadAllocatedBytes()
