### ISSUE TITLE
Document jdk11 compact strings known issue

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1341]
**Subject:**
https://github.com/eclipse-openj9/openj9/blob/master/doc/release-notes/0.44/0.44.md

**Suggestion:**
Document https://github.com/ibmruntimes/openj9-openjdk-jdk22/issues/60 as a known issue for jdk11 with the workaround

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - What exactly is the problem and why was it happening? Thanks!

**Comment by pshipton** [comment]
Using a String created by spit(), from a String that contains non-Latin1 characters, with indexOf() may return an incorrect result. The problem is caused by compact strings, which was enabled by default in 11.0.21. The workaround is to disable compact strings via `-XX:-CompactStrings` or use Java 17 or later. The bug will be resolved in the next release.
