### ISSUE TITLE
Changes to the JITServerUseAOTCache and JITServerShareROMClasses options

### ISSUE THREAD

**Issue by cjjdespres** [eclipse-openj9/openj9-docs#1350]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19585
https://github.com/eclipse-openj9/openj9/pull/19619

**Overview:**

The `-XX:+JITServerUseAOTCache` option is on by default at a JITServer. It is still disabled by default for JITServer clients. That means that that option does not need to be specified at the server to enable the JITServer AOT caching feature, but still needs to be specified for each client wishing to use the feature. This change is for user convenience. I think the documenation for that option itself and the AOT cache section of `jitserver_tuning.md` both need to be updated.

A related change: the option `-XX:+JITServerShareROMClasses` is now effectively on by default due to the change above, as ROM class sharing is enabled at a JITServer by default when the AOT cache is enabled at a JITServer. This should result in reduced server memory usage in the default configuration.

**Release target:**
OpenJ9 0.46.0

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All platforms supporting JITServer (Linux - X, P, Z).

**Comment by cjjdespres** [comment]
Attn @mpirvu. Should the AOT cache documentation also be updated to reflect the fact that the local SCC is ignored by default?

**Comment by Sreekala-Gopakumar** [comment]
> Attn @mpirvu. Should the AOT cache documentation also be updated to reflect the fact that the local SCC is ignored by default?

@cjjdespres @mpirvu - Any action on this?

**Comment by mpirvu** [comment]
Yes, we need an update of the documentation for release 0.46.0

**Comment by cjjdespres** [comment]
If that's the case then the documentation also needs to be updated to remove the requirement that `-Xshareclasses` be set up at a client for the server AOT cache to be used. Specifically:

- In the `-XX:[+|-]JITServerUseAOTCache` documentation, the requirement that the client have the shared classes feature enabled can be dropped entirely

- In the JITServer tuning page, this paragraph:

> If the JITServer AOT cache feature and the [-Xshareclasses:readonly](https://eclipse.dev/openj9/docs/xshareclasses/#readonly) option are both enabled at the same time at a JITServer client, the shared classes cache startup creates a temporary new (writable) top layer that the JITServer AOT cache can use to store data that it needs to function.

can be deleted entirely.

- In "JITServer AOT cache section" of the JITServer tuning article, this sentence:

> This mechanism works in conjunction with the [dynamic AOT technology](https://www.eclipse.org/openj9/docs/aot/) at the client and therefore the client needs to have the [shared classes cache](https://www.eclipse.org/openj9/docs/shrc/) (SCC) enabled (the SCC is the repository for the AOT code).

can have the "and therefore the client..." part deleted entirely.

- I think the release notes can also mention that the SCC feature does not need to be set up for JITServer clients to use `-XX:+JITServerUseAOTCache`. That's an ease-of-use change that shouldn't otherwise affect the feature.
