### ISSUE TITLE
Add option to toggle Extended HCR capability

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9-docs#1352]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19554

**Overview:**
A new option `-XX:[+|-]EnableExtendedHCR` is added. This option toggles the extended HCR capability in the JVM. 

Note: by default this capability is disabled (for Semeru but not IBM Java 8) which is a change in behaviour from previous releases. If there is a JVMTI failure as a result of this change, the user will see the following warning message `Warning: Extended HCR is disabled, enable with -XX:+EnableExtendedHCR.`. 

Also, as part of this change we will be announcing the deprecation of the extendedHCR feature for removal in the near future. As of JDK25 extended HCR will no longer be supported. Following that, we will also remove extended HCR support from legacy releases (ie. JDK8).

**Release target:**
Eclipse OpenJ9 0.46.0*

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: *-XX:[+|-]EnableExtendedHCR*
- Purpose: This option toggles the extended HCR capability in the JVM. 
- Restrictions: None

**Comment by tajila** [comment]
@pshipton @mstoodle any concerns with the deprecation statement?

**Comment by tajila** [comment]
For background:

Short-term requirement: We need to disable extendedHCR to support unsafe static field access at fixed offsets optimization. The dynamic checks are not ideal, but it is what we have to do now.

Long-term requirement: There is a maintenance cost is supporting extended HCR and we are not sure anyone is actually using it. The ideal scenario is to just remove the feature entirely.

**Comment by pshipton** [comment]
Seems fine.

**Comment by pshipton** [comment]
How does this apply to IBM Java 8, considering it's not disabled by default there atm?

**Comment by tajila** [comment]
> How does this apply to IBM Java 8, considering it's not disabled by default there atm?

I assumed we didn't document IBM java8 in openj9 docs

**Comment by mstoodle** [comment]
I'm fine with the approach so long as there is a way for us to discover that lots of people do depend on it.

We should possibly add this option to any migration documentation we have between IBM SDK for Java and Semeru Runtimes (but that's something for IBM to decide and shouldn't block openj9 moving forward with this approach).

**Comment by tajila** [comment]
> Also I'm curious how your plan to "remove extended HCR support from legacy releases" affects IBM Java 8. Is it exempt?

This round we will disable it in Semeru/Openj9 by default. Next release, I'd like to disable it in IBM Java8 assuming no one complains. Afterwards, I'd like to remove it completely.

**Comment by tajila** [comment]
> > Also I'm curious how your plan to "remove extended HCR support from legacy releases" affects IBM Java 8. Is it exempt?

> This round we will disable it in Semeru/Openj9 by default. Next release, I'd like to disable it in IBM Java8 assuming no one complains. Afterwards, I'd like to remove it completely.

Now that I think about it, I think we need a stronger deprecation message. Something like: `Warning: Extended HCR is disabled, enable with -XX:+EnableExtendedHCR. In the future, this capability will be removed from the JDK`

**Comment by pshipton** [comment]
We should add something to this migration guide.
https://www.ibm.com/support/pages/semeru-runtimes-migration-guide

**Comment by pshipton** [comment]
I'll let @Sreekala-Gopakumar answer that.

**Comment by Sreekala-Gopakumar** [comment]
Yes, we can change the migration guide.

**Comment by Sreekala-Gopakumar** [comment]
> We should add something to this migration guide. https://www.ibm.com/support/pages/semeru-runtimes-migration-guide

@pshipton - I have updated the migration guide. Please check and confirm that the content is ok. Thanks!

https://supportcontent.ibm.com/support/pages/node/6366719/latest

**Comment by pshipton** [comment]
Looking at this again, we should expand the one line description. It says `New -XX:[+|-]EnableExtendedHCR option added` but doesn't mention the change in behavior.

**Comment by pshipton** [comment]
I suggest the migration item should mention the change in behavior occurs in the OpenJ9 0.46 release, or the following OpenJDK versions: jdk8u422, 11.0.24, 17.0.12, 21.0.4, 22.0.2, 23.0

**Comment by pshipton** [comment]
Looks good.
