### ISSUE TITLE
-Xshareclasses automatically turns on -XX:+ShareOrphans

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9-docs#1354]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19679

**Overview:**
OpenJ9 introduced options `-XX:+ShareOrphans` and `-XX:-ShareOrphans` in 0.46 release. See https://github.com/eclipse-openj9/openj9-docs/issues/1330. User has to explicitly specify `-XX:+ShareOrphans` to turn on this feature. In 0.47 release, if option `-Xshareclasses` is specified in the command line, it automatically turns on `-XX:+ShareOrphans`.

**Release target:**
Eclipse OpenJ9 0.47

**Applies to the following JDK versions:**
All versions

**Applies to the following platforms:**
All platforms

**Comment by Sreekala-Gopakumar** [comment]
In the documentation, we have mentioned that the " `-XX:+ShareOrphans` option automatically enables the `-Xshareclasses` option." So, now with this change, whichever option is enabled first, the other option will be enabled automatically? Is my understanding correct?

**Comment by Sreekala-Gopakumar** [comment]
Also, please refer to https://github.com/eclipse-openj9/openj9-docs/pull/1383#discussion_r1695746485 regarding the following 2 known problems.

> The class comparison might not detect the removal of method access modifiers. For example, a change of a method from public to package-private.
> java.lang.StackTraceElement.getClassLoaderName() might return null for classes that are stored in the shared cache.

As per your comment in https://github.com/eclipse-openj9/openj9-docs/issues/1330#issue-2286246234, are these 2 known problems now fixed in 0.47.0 release?

**Comment by hangshao0** [comment]
> As per your comment in https://github.com/eclipse-openj9/openj9-docs/issues/1330#issue-2286246234, are these 2 known problems now fixed in 0.47.0 release?

Yes.
