### ISSUE TITLE
Remove RHEL/CentOS versions which are out of public support

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#1365]
**Subject:**
https://eclipse.dev/openj9/docs/openj9_support/

**Suggestion:**
Remove:
CentOS 6.10
Red Hat Enterprise Linux (RHEL) 6.10
CentOS 7.9
RHEL 7.8

Update:
RHEL 8.6 to 8.8
RHEL 9.0 to 9.2

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Based on the changes in this issue, what should be changed in the [Build environments](openj9_support.md#build-environments) section, Operating system columns? Thanks!

**Comment by pshipton** [comment]
> Based on the changes in this issue, what should be changed in the [Build environments](https://github.com/eclipse-openj9/openj9-docs/issues/openj9_support.md#build-environments) section, Operating system columns?

Nothing, the build environments aren't changing.
