### ISSUE TITLE
CRIU enable JDWP support post-restore

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse-openj9/openj9-docs#1407]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/19754
https://github.com/eclipse-openj9/openj9/pull/19405
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/591

**Overview:**
Enable JDWP support post-restore via the following means:
* Supply a command line option `-agentlib:jdwp` or `-Xrunjdwp` pre-checkpoint, the JVM will be suspended upon CRIU restore unless `suspendOnRestore=n` is specified;
* When there is no such command line option pre-checkpoint, `-agentlib:jdwp` or `-Xrunjdwp` can be provided in a restore option file specified via the `CRIUSupport.registerRestoreOptionsFile()`.

**Release target:**
Eclipse OpenJ9 0.48.0

**Applies to the following JDK versions:**
11 and later

**Applies to the following platforms:**
Linux X|P|Z|A

**For new command line options:**

- Option name and syntax: 
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=[y|n],suspendOnRestore=[y|n]
  -Xrunjdwp:transport=dt_socket,server=y,suspend=[y|n],suspendOnRestore=[y|n]

- If values are set pre-checkpoint:
	- suspend=y - the JVM will be suspended pre-checkpoint, and post-restore unless suspendOnRestore=n
	- suspend=n - the JVM will not be suspended pre-checkpoint, and suspended post-restore unless suspendOnRestore=n
- If values are set within a restore option file:
	The JVM will be suspended post-restore unless suspendOnRestore=n
- Purpose:
	This option allows the Java application to be debugged via a JDWP agent post-restore.
- Restrictions:
	- Can only be used with `-XX:+DebugOnRestore -XX:+EnableCRIUSuport`

**Comment by JasonFengJ9** [comment]
> What is the difference between -agentlib:jdwp or -Xrunjdwp options?

`-Xrunjdwp` (along with `-Xdebug`) is for Java releases before 5.0 to load the JDWP agent. `-agentlib:jdwp` is for JDK 5+ though `-Xrunjdwp` is still supported for back compatibility. So there is no difference from the CRIU JDWP support perspective.

> What are the criteria based on which the user should choose to use either of these options? When should the user use -agentlib:jdwp and when -Xrunjdwp?

A user can choose either one. `-agentlib:jdwp` option is preferable as per this [Oracle guide doc](https://docs.oracle.com/javase/1.5.0/docs/guide/jpda/conninv.html)

> We have listed different kinds of command-line options in our user guide - System property, standard options, -X options, and -XX options (https://eclipse.dev/openj9/docs/cmdline_specifying/). Under which category can we add the -agentlib:jdwp option? Standard option?

Standard option.

> What is the meaning of the transport=dt_socket variable? Does the transport variable have any other value?

`transport` is the name of the transport to use in connecting to the debugger application. There are other values such as `dt_shmem` for Windows platforms, more details are in Oracle doc [Connection and Invocation Details](https://docs.oracle.com/en/java/javase/11/docs/specs/jpda/conninv.html)

> What are the default values of all the specified variables for both the command line options? transport=dt_socket,server=y,suspend=[y|n],suspendOnRestore=[y|n]

`suspend` is an OpenJDK option which is `true` by default.
`suspendOnRestore` is `true`, i.e., the JVM will be suspended post-restore unless `suspendOnRestore=n`.

**Comment by Sreekala-Gopakumar** [comment]
> > What is the difference between -agentlib:jdwp or -Xrunjdwp options?
> 
> `-Xrunjdwp` (along with `-Xdebug`) is for Java releases before 5.0 to load the JDWP agent. `-agentlib:jdwp` is for JDK 5+ though `-Xrunjdwp` is still supported for back compatibility. So there is no difference from the CRIU JDWP support perspective.
> 

Here you have specified that the the options are applicable for Java releases before 5.0 and for JDK 5+ but in the main comment (https://github.com/eclipse-openj9/openj9-docs/issues/1407#issue-2525400203), you have specified that these options **Applies to the following JDK versions: 11 and later**. 

Do you mean to say that these options were available before OpenJDK 5 (`-Xrunjdwp`) and for OpenJDK 5 and later (`agent lib:jdwp`) but we can use these options to enable JDWP support on restore only on OpenJDK 11 and later?

Thanks!

**Comment by Sreekala-Gopakumar** [comment]
What was the reason for introducing this new parameter `suspendOnRestore` instead of using `suspend`? What was going wrong? Java debugging was not happening after restore?

Difference between `suspend` and `suspendOnRestore`? If `suspend` was set as `n` at checkpoint, was it automatically changing to `y` on restore?

**Comment by JasonFengJ9** [comment]
>>> What is the difference between -agentlib:jdwp or -Xrunjdwp options?

>> -Xrunjdwp (along with -Xdebug) is for Java releases before 5.0 to load the JDWP agent. -agentlib:jdwp is for JDK 5+ though -Xrunjdwp is still supported for back compatibility. So there is no difference from the CRIU JDWP support perspective.

> Here you have specified that the the options are applicable for Java releases before 5.0 and for JDK 5+ but in the main comment (https://github.com/eclipse-openj9/openj9-docs/issues/1407#issue-2525400203), you have specified that these options Applies to the following JDK versions: 11 and later.

> Do you mean to say that these options were available before OpenJDK 5 (-Xrunjdwp) and for OpenJDK 5 and later (agent lib:jdwp) but the suspendOnRestore parameter was added to enable JDWP support on restore only on OpenJDK 11 and later?

Only `-Xrunjdwp` is supported before OpenJDK 5.
Both `-Xrunjdwp` and `-agentlib:jdwp` are supported since OpenJDK 5.
CRIU including this option is available on JDK 11+, and supports both `-Xrunjdwp` and `-agentlib:jdwp`.

**Comment by Sreekala-Gopakumar** [comment]
When you say " the JVM will be suspended upon CRIU restore", which VM will be suspended? 

Or do we mean that the "debugging" will be suspended on restore because the debugging sessions do not persist across checkpoints?

**Comment by JasonFengJ9** [comment]
> When you say " the JVM will be suspended upon CRIU restore", which VM will be suspended?

There is only one VM which runs pre-checkpoint and post-restore.

> Or do we mean that the "debugging" will be suspended on restore because the debugging sessions do not persist across checkpoints?

The debugging sessions do not persist across checkpoints.
There are use cases with no debugging pre-checkpoint, and the debugging is enabled for post-restore.
The debugger registers the post-restore event, receives notification upon CRIU restore, and suspends the VM unless `suspendOnRestore=n` is specified.
