### ISSUE TITLE
Document additional jcmd options

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse-openj9/openj9-docs#343]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/6521

**Overview:**
-f: read commands from a file
select VMs by main class instead of VMID
select all VMs if VMID==0
Update help text accordingly:

jcmd <vmid | class> <arguments>
...
    <main class>: string used to select processes from the full list; may be a substring of a fully qualified class name
...
    -f <command file>: read command from a file, one command per line
...
      A <vmid> of 0 indicates that the command should be applied to all Java processes. 

**Release target:**
TBD: @pshipton 
**Applies to the following JDK versions:**
all

**Applies to the following platforms:**
all

**For new command line options:**

@jasonfengj9 to document when implemented.

**Comment by SueChaplain** [comment]
@JasonFengJ9 - do you see any new work coming for this or can we close please?

**Comment by JasonFengJ9** [comment]
A new work `Jcmd dump with default settings` has been documented via https://github.com/eclipse-openj9/openj9-docs/pull/545
There are no new comings.
We can add doc along with new code implementation which is a requirement anyway.
