### ISSUE TITLE
Add support for Hotspot Objectheap/Codecache options

### ISSUE THREAD

**Issue by AlenBadel** [eclipse-openj9/openj9-docs#459]
See associated OpenJ9 PR
https://github.com/eclipse/openj9/pull/7476

Overview:
To mitigate the effort required for users to migrate to OpenJ9 from Hotspot the following options have been added. 

-XX:LargePageSizeInBytes=<size> equivalent to -Xlp:Codecache:pagesize=<size> and -Xlp:Objectheap:pagesize<size>.

-XX:+UseLargePages both the objectheap and codecache use the largest available large page sizes available on the system. 

Release target:
Eclipse OpenJ9 ~~0.18.0 0.19.0 0.20.0. 0.21.0~~

Applies to the following JDK versions:
8 and later

Applies to the following platforms:
All platforms

For new command line options:

-XX:LargePageSizeInBytes=<size>
Size can be either Integer values, or a mixture of Integer values followed a prefix (K/M/G) to signify the magnitude of the large pages. 
There is no range restriction as the algorithm will try to find the closest supported large page. 

-XX:+UseLargePages
(Uses no further arguments)

**Comment by SueChaplain** [comment]
Very similar to #453 in terms of the updates needed.

**Comment by SueChaplain** [comment]
OpenJ9 issue is closed and marked as obsolete. Closing this issue too.

>Closing as this is obsoleted by #8671
