### ISSUE TITLE
Allow double mapping by default on Linux Platforms

### ISSUE THREAD

**Issue by bragaigor** [eclipse-openj9/openj9-docs#475]
**Issue or pull request number:**
*https://github.com/eclipse/openj9-docs/pull/476*

**Overview:**
*Large arrays in balanced garbage collection gets allocated discontiguously (in different regions). Double mapping allows the GC to have a contiguous view of the array without having to rely on iterators. One example of double mapping's benefits is JNI critical, which requires a contiguous view of an array. Without double mapping JNI critical first needs to copy element by element the entire array to a temporary one; second, perform its operation and third, copy all the elements back to the original array. This is extremely expensive. With double mapping, JNI critical can perform its operation on the contiguous representation of the array where its changes gets reflected on the original discontiguous array, without the need to copy any element. For such operations double mapping proved to be 20 times faster on average. For more information please refer to the blog post: https://eclipse-omr.org/double-map-arraylets/*

**Current limitations:**
*Double mapping does not support systems that has huge pages as default (normally 2MB). In such systems if double mapping is requested, it will get disabled. Please see: https://github.com/eclipse/openj9/pull/8254*

**Release target:**
*Eclipse OpenJ9 ~~0.18.0 0.19.0 0.20.0 0.21.0~~*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P*

**For new command line options:**
- Option name and syntax: 
*-XXgc:enableArrayletDoubleMapping*
*-XXgc:disableArrayletDoubleMapping*

- Default value: *-XXgc:enableArrayletDoubleMapping*

**Comment by pshipton** [comment]
It's too late for the 0.18.0 release. If the change is delivered by Feb 9 it can be in the 0.19.0 release, although this release is for Java 14 only.

**Comment by amicic** [comment]
We can probably wait for next Java 8/11. Is that 0.20, and when?

**Comment by pshipton** [comment]
0.20 ships mid April. We haven't set a branch date yet, but tentatively March 8.

**Comment by DanHeidinga** [comment]
> We can probably wait for next Java 8/11. Is that 0.20, and when?

Why would we hold the code for that?  I'd rather get it out to users so they can benefit from it and we can get more feedback on it

**Comment by amicic** [comment]
I'd rather soak it for several weeks (when is 0.20) in nightly and perf testing. There are techniques and OS APIs that we have not relied on in past - there is potential risk. 
On the other side, the problem this fixes have been around ever since Balanced was introduced and no customer complained.

**Comment by amicic** [comment]
We are just about to enable it, so it will go to 0.19 anyway, right?
BTW, there is a way to disable the feature, in a case something goes wrong.

**Comment by bragaigor** [comment]
#476 has been merged. Closing this issue.

**Comment by pmhayward** [comment]
Reopening as new documentation still needs to be edited.

**Comment by SueChaplain** [comment]
Closing, see #517
