### ISSUE TITLE
Documentation changes for Class Relationship Verification Snippets work

### ISSUE THREAD

**Issue by sharon-wang** [eclipse-openj9/openj9-docs#490]
**Issue or pull request number:**
https://github.com/eclipse/openj9/pull/8420

**Overview:**
Further work has been done related to `-XX:[+|-]ClassRelationshipVerifier` as described in the PR above. A new command-line option has been introduced `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC` (detailed below), and changes to existing documentation are needed (also detailed below).

**Release target:**
TBD, will update once known

**Applies to the following JDK versions:**
All

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC`
- Purpose: This option enables and disables the recording of class relationships in the verifier to delay validation until triggered by class loading, but does not use the Shared Classes Cache (SCC) to do so.
- Restrictions: You cannot use this setting in conjunction with -Xfuture or -Xverify:all, which itself enables -Xfuture.
- Notes: this new option provides the same function as `-XX:[+|-]ClassRelationshipVerifier`, except that it ignores the SCC. The documentation for this option will be roughly the same as https://www.eclipse.org/openj9/docs/xxclassrelationshipverifier/

**Updates to existing documentation:**
- -Xfuture and -Xverify documentation needs to mention incompatibility with `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC`
- `-XX:[+|-]ClassRelationshipVerifier` should refer to `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC` and vice versa
- https://www.eclipse.org/openj9/docs/shrc_diag_util/#printstats, https://www.eclipse.org/openj9/docs/shrc_diag_util/#printtoplayerstats, https://www.eclipse.org/openj9/docs/dump_javadump/#shared-classes all need to be updated to include the new cache data type for snippets

A brief explanation describing the difference between `-XX:[+|-]ClassRelationshipVerifier` and `-XX:[+|-]ClassRelationshipVerifierIgnoreSCC` should be included in the release doc. Can refer to: https://www.eclipse.org/openj9/docs/version0.17/#option-to-record-class-relationships-in-the-verifier

Lastly, documentation for the release that this change goes into will need to mention that the shared classes cache generation number has been updated, similar to: https://www.eclipse.org/openj9/docs/version0.14/#changes-to-the-shared-classes-cache-generation-number

**Comment by SueChaplain** [comment]
Closing, see #494
