### ISSUE TITLE
Reinstate Balanced GC double mapping info for future release

### ISSUE THREAD

**Issue by pmhayward** [eclipse-openj9/openj9-docs#517]
See #476 for originating issue with PR info and template info.

Balanced GC double mapping was included in 0.19 then removed. 

When the 'Balanced policy' section is reinstated in gc.md:

- The balanced policy should be removed from the 'Other policies' section.
- Double mapping must be included in 'What's new'. 
- The entry for this policy in the -Xgcpolicy topic (xgc.md) might need adjusting as well, including link to [Balanced Garbage Collection policy](https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/mm_gc_balanced.html) in KC. (Does information in that KC topic and sub-tops not already covered need transferring to OpenJ9 docs?)

**Comment by pshipton** [comment]
Double mapping isn't going to be reinstated for 0.20.0, but in some future release TBD.

**Comment by amicic** [comment]
There was some general background info about Balanced GC in the original @bragaigor  update. We could extract and release that part. But anything that talks about double mapping should not go out -  as @pshipton stated, it's unknown at this point when it will be available.

**Comment by SueChaplain** [comment]
There are no plans to reinstate this as is. Closing this issue. A new issue will be created in the future.
