### ISSUE TITLE
New command line option: -Xgc:dynamicBreadthFirstScanOrdering

### ISSUE THREAD

**Issue by jonoommen** [eclipse-openj9/openj9-docs#703]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/7552

**Overview:**
Sets GC scan order to a dynamic breadth-first order. This new scan ordering is a layer on top of the existing breadth-first scan ordering implementation. This dynamic breadth-first scan ordering uses JIT information to determine the hot access paths (fields that are often accessed within a class) of an object and when a live object is being copied during a GC, the collector will recursively copy the hot fields of the object currently being copied (if any hot fields exist) along with the hot fields of the hot fields, etc. until a class containing zero hot fields in reached. At this time, the GC will continue to scan objects in a breadth-first order until another object that contains hot fields is copied. At that point, the cycle repeats to recursively depth copy the hot fields of the object immediately after the parent object is copied.

**Release target:**
Eclipse OpenJ9 ~~0.25.0~~ ~~0.26.0~~ 0.27.0

**Applies to the following JDK versions:**
8 and later 

**Applies to the following platforms:**
All platforms 

**New command-line option:**
- Option name and syntax: -Xgc:dynamicBreadthFirstScanOrdering
- Default value: -Xgc:breadthFirstScanOrdering for the "balanced" GC policy and -Xgc:hierarchicalScanOrdering for the 
	default "gencon" GC policy

- Purpose:
This new scan ordering enables the possibility to spatially localize, in memory, objects accessed frequently together. This new scan ordering policy will likely result in a better cache hit ratio compared to a standard breadth-first scan ordering, leading to increased overall application throughput at a low overhead cost.

- Restrictions:
Only applicable to "gencon" and "balanced" GC policies

**Comment by dmitripivkine** [comment]
I believe this feature is not targeted for 0.24 release, but next one.

**Comment by jonoommen** [comment]
@dmitripivkine I thought the idea was that this feature is part of release 0.24, but the next release is where it will be enabled by default in balanced. For now, it is available via command-line option but never on by default. From our discussion previously I believe it was only enabling this by default in balanced that was supposed to wait until the next version, or would be I incorrect?

**Comment by SueChaplain** [comment]
@jonoommen and @dmitripivkine 
Work not started until we get clarity over the target release. Given the lateness, and the fact that this is not enabled by default, I would prefer to target this for 0.25.0 ... at least that is my opinion.

Other questions:

>Option name and syntax: -Xgc:dynamicBreadthFirstScanOrdering

>Default value: -Xgc:breadthFirstScanOrdering for the "balanced" GC policy and -Xgc:hierarchicalScanOrdering for the
default "gencon" GC policy

I don't understand this. Are there 3 options to document or is this actually a `-Xgc:[+|-]dynamicBreadthFirstScanOrdering` type option where you have aliased the different strategies under the covers? i.e `+` = balanced only enabled 

The -XXgc options do not seem like options an end user would have any chance of successfully using unless they were a GC developer. I'm not sure they should be documented .... infact I thought that these were not going to be exposed. @pshipton ??

**Comment by pshipton** [comment]
My advice is to be consistent. If the -XXgc options are documented in the upcoming blog, they should also be documented in the user guide. Also, if these options could be provided to customers and used in production, they should be documented.

**Comment by amicic** [comment]
We should not expose those fine tuning options via a blog and no need to document

**Comment by SueChaplain** [comment]
Bumping to 0.25.0 as agreed with Aleks

**Comment by jonoommen** [comment]
I will update the blog and this issue to reflect this 👍

**Comment by SueChaplain** [comment]
@jonoommen - time to document these changes for 0.25.0. Please can you answer the question I had in an earlier comment:

>I don't understand this. Are there 3 options to document or is this actually a -Xgc:[+|-]dynamicBreadthFirstScanOrdering type option where you have aliased the different strategies under the covers? i.e + = balanced only enabled

**Comment by jonoommen** [comment]
Ok, will do @SueChaplain. As for your question, currently, there is no documentation that I can find for `Xgc:breadthFirstScanOrdering` or `Xgc:hierarchicalScanOrdering`. I would have thought that only documentation for one option (`Xgc:dynamicBreadthFirstScanOrdering`) would need to be added and it would just append the documentation where `Xgc:breadthFirstScanOrdering` and `Xgc:hierarchicalScanOrdering` are found as they have been around for years. I believe documentation should be added for all 3 of these options or none of them (as currently).  As this is an -Xgc and not a -XXgc option, I believe all 3 should have documentation. What are your thoughts @pshipton @amicic @dmitripivkine?

**Comment by dmitripivkine** [comment]
I think because we decided to postpone changing scan ordering default for Balanced to 0.26 https://github.com/eclipse/openj9/pull/11576 we can move this item to Milestone 0.26 too (otherwise it would required immediate editing of default for Balanced)

**Comment by dmitripivkine** [comment]
Scan Ordering is applicable for Copy Collectors as Scavenger in Gencon and CopyForward in Balanced. Historically there were two mutually exclusive modes (policies): Breadth First and Hierarchical. Now we are adding a third one - Dynamic Breadth First. I agree the article about Scan Ordering might be a complicate one. I believe it is a reason why these options have not been documented before. Instead we just provide best option available.
I believe the current concern is despite we think newly introduced Dynamic Breadth First is a best choice for Balanced it might potentially cause performance degradation for some customers. In order to simplify return back to previous Scan Ordering policy if necessary looks like we should make these options documented and publicly available.

**Comment by jonoommen** [comment]
From a discussion offline with @amicic and @dmitripivkine, the decision is to provide basic documentation for these 3 options, but nothing overly deep.

**Comment by amicic** [comment]
So, we basically need to say that we have a few variants of object graph traversal in evacuating style of GCs (Scavenge in Genbcon and PGC in Balanced). As a consequence, object layout may be affected, therefore object/reference locality and therefore app throughput.

Both GCs support plain Breadth First (well known as Cheney's algorithm, and that can be mentioned). There is even wikipedia article, but just for you (no necessary to refer to it): https://en.wikipedia.org/wiki/Cheney's_algorithm

Then, we say that we have two other variants that use partial Depth First traversal on top of Breath First, one driven by minimizing object distances (Hierachical, gencon only) and the other driven by object field hotness (Dynamic, both gencon/Balanced). That's all about technical details. 

We state what defaults are, and that they are picked as known to be the best, but that specific workloads in some/rare cases may perform marginally better with other ones.

**Comment by SueChaplain** [comment]
OK - thanks for update. I've moved this to the 0.26 April milestone

**Comment by dmitripivkine** [comment]
There is another attempt to introduce this option
