### ISSUE TITLE
Adaptive GC Threading Documentation Updates

### ISSUE THREAD

**Issue by RSalman** [eclipse-openj9/openj9-docs#766]
**Issue or pull request number:**
https://github.com/eclipse/openj9-docs/pull/765

**Overview:**
With the introduction of Adaptive GC Threading optimization (eclipse/openj9#11999 &
eclipse/omr#5830), new options need to documented and some of the existing options need to be updated for clarification.

Discussion on the behaviour, naming and interaction with existing options can be found at eclipse/openj9#12119.

**Release target:**
Eclipse OpenJ9 0.27.0

**Applies to the following JDK versions:**
8 and Later

**Applies to the following platforms:**
All platforms (Only applicable to the default GC GENCON Policy)

**For new command line options:**
XX:
-XX:[+-]AdaptiveGCThreading to enable/disable the GC adaptive threading optimization.
-XX:ParallelGCMaxThreads= Mapped to Xgcmaxthreads (see below)

Xgc:
-Xgcmaxthreads The max number of threads available to Adaptive Threading (Similar to Xgcthreads, except it doesn’t set enforce thread count). for default value/range of values see existing `Xgcthreads` option

Existing Xgcthreads & XX:ParallelGCThreads= option pages updated with notes to compare with new options.

**Comment by RSalman** [comment]
@pshipton could you please confirm that the changes are Applies to JDK versions *8 and Later*

**Comment by pshipton** [comment]
Yes, the same OpenJ9 code stream applied to all jdk8, jdk11, jdk16, and the future jdk17+

**Comment by SueChaplain** [comment]
Closed by #765.
