### ISSUE TITLE
Increase OS stackspace on PPC64

### ISSUE THREAD

**Issue by tajila** [eclipse-openj9/openj9-docs#776]
**Issue or pull request number:**
https://github.com/eclipse/openj9/issues/12416
https://github.com/eclipse/openj9/pull/12501

**Overview:**
Increase OS stackspace on PPC64 to 512KB

**Release target:**
E.g. Eclipse OpenJ9 0.27.0

**Applies to the following JDK versions:**
JDK 8, 11, 16 and onwards

**Applies to the following platforms:**
AIX and Linux P 64bit

- Purpose:
Increases availble stack space on the OS threads as the stack space requirements have been increased in order to persist vector registers between internal VM calls.

- Restrictions:
None.

**Comment by SueChaplain** [comment]
@tajila - did you mean release target 0.27.0? We just published 0.26.0.

**Comment by tajila** [comment]
My mistake. Yes, 0.27.0.
