### ISSUE TITLE
Document new jpackcore/jextract option

### ISSUE THREAD

**Issue by keithc-ca** [eclipse-openj9/openj9-docs#802]
https://github.com/eclipse-openj9/openj9/pull/13194

**Overview:**
See https://github.com/eclipse-openj9/openj9/issues/12344.

**Release target:**
Eclipse OpenJ9 0.27.0

**For new command line options:**

- Option name and syntax: *-x*
- Purpose: omit system dump file from resulting archive

**Comment by doveye** [comment]
@keith-ca is this really for 0.27? If so,  we need doc updates ASAP (and also an addition to the [release notes](https://github.com/eclipse-openj9/openj9/blob/master/doc/release-notes/0.27/0.27.md))

**Comment by keithc-ca** [comment]
Yes, this should be done for 0.27.0; see eclipse-openj9/openj9#13228 for the addition to the release notes. I'll update openj9-docs next.

**Comment by keithc-ca** [comment]
See #808 for the documentation update.
