### ISSUE TITLE
-Xmint/-Xmaxt descriptions misleading

### ISSUE THREAD

**Issue by cedrichansen** [eclipse-openj9/openj9-docs#803]
**Subject:**
*-Xmint/-Xmaxt page*

https://www.eclipse.org/openj9/docs/xmint/ describes the option correctly, but provides a misleading default values.
The default values are displayed as follows
Setting | Effect | Default
-- | -- | --
-Xmint<value> | Set minimum time in GC | 5
-Xmaxt<value> | Set maximum time in GC | 13

Users would then think that they could specify

`-Xmint5 -Xmaxt10` on the command line, but this causes the following JVM initialization error

```
$ ./java -Xmint5 -Xmaxt10 -version
JVMJ9GC033E -Xmaxt value must be between 0.00 and 1.00 (inclusive)
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to initialize; unable to parse command line
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Rather, the correct format for 5% & 10% is `-Xmint0.05 -Xmaxt0.10`

**Suggestion:**
Display the defaults as follows

Setting | Effect | Default
-- | -- | --
-Xmint<value> | Set minimum time in GC | 0.05 
-Xmaxt<value> | Set maximum time in GC | 0.13

`-Xminf/-Xmaxf` is consistent with how the option should be specified in this regard (example/default is 0.0-1.0 based)
as is `-Xloainitial / -Xloaminimum / -Xloamaximum`

**Comment by cedrichansen** [comment]
@amicic @dmitripivkine fyi

**Comment by doveye** [comment]
The docs have been updated
