### ISSUE TITLE
-XX:HeapDumpPath support not documented

### ISSUE THREAD

**Issue by gjdeval** [eclipse-openj9/openj9-docs#812]
According to https://github.com/eclipse-openj9/openj9/pull/2508 the option -XX:HeapDumpPath is supported by OpenJ9, but it does not appear in the documentation at https://www.eclipse.org/openj9/docs

**Comment by doveye** [comment]
I checked and a topic does exist for [-XX:HeapDumpPath](https://www.eclipse.org/openj9/docs/xxheapdumppath/) plus it's in the OpenJ9-Hotspot mapping topic at https://www.eclipse.org/openj9/docs/cmdline_migration/. These changes were made in 2018. The first topic can be found via the table of contents but search doesn't find either "-XX:HeapDumpPath" or "heapdumppath". There's already an issue open for search failures so I'll close this one.
