### ISSUE TITLE
`-Xsoftmx` now applies to nursery + tenure for Gencon GC

### ISSUE THREAD

**Issue by cedrichansen** [eclipse-openj9/openj9-docs#813]
**Issue or pull request number:**
~~https://github.com/eclipse/omr/pull/6120~~
EDIT: https://github.com/eclipse-openj9/openj9/pull/13481

**Overview:**
Softmx will now apply to both nursery AND tenure for gencon gc policy.

The proportion of softmx that will be used for nursery, will be proportional to Xmnx/Xmx (1/4 by default), while the remainder of the space will be used for tenure.

Ex. If `-Xsoftmx5G -Xmnx2G -Xmx10G` is specified, the softmx for nursery portion of the heap is (2/10) * 5 = 1G. This would leave 4G of softmx space for tenure. The previous behaviour would leave all 5G of softmx space for tenure, and allow nursery to resize however it wanted

The behaviour is now:
Nursery + tenure <= softmx 

Old behaviour was:
tenure <= softmx

With this, the following block of text in softmx docs should be removed
```
When using -Xgcpolicy:gencon, -Xsoftmx applies only to the tenure area of the heap. In some cases the heap grows to greater than the -Xsoftmx value because the nursery portion grows, making the heap size exceed the limit that is set. See -Xmn for limiting the nursery size.
```

**Release target:**
Eclipse OpenJ9 ~~0.28~~ 0.29

**Applies to the following JDK versions:**
all versions

**Applies to the following platforms:**
all platforms

**For new command line options:**
No new options

**Comment by dmitripivkine** [comment]
This code has been reverted due compile problem on one of platforms. As a result it was not in at the code freeze time for 0.28.0 (Java 17). This is not essential fix but improvement of behaviour existed for years. Move it to 0.29.0 milestone

**Comment by cedrichansen** [comment]
As of https://github.com/eclipse-openj9/openj9/pull/13481, this change has been fixed, and re-introduced.
