### ISSUE TITLE
Add OpenJ9 API documentation to support the Java 17 LTS release

### ISSUE THREAD

**Issue by doveye** [eclipse-openj9/openj9-docs#820]
**Issue or pull request number:**
Various

**Overview:**
Add Java 17 API documentation (and remove Java 16 API doc)

**Release target:**
Eclipse OpenJ9 0.28.0 (so the API doc will need to be created from the v0.28.0-release branch)

**Applies to the following JDK versions:**
17 only

**Applies to the following platforms:**
All platforms

**Comment by pshipton** [comment]
This was completed.
