### ISSUE TITLE
Update supported platforms topic for 0.28.0 (supports Java 17)

### ISSUE THREAD

**Issue by doveye** [eclipse-openj9/openj9-docs#822]
**Subject:**
- Update https://www.eclipse.org/openj9/docs/openj9_support/ with changes for 0.28.0, including changes for Java 17.

**Suggestion:**
- Update the "Eclipse OpenJ9 releases" table. Remove the note (1) saying that 0.28 is a future release. Add more future releases and remove older ones. Do we want to remove the JDK 16 column? (I think I remember that in the past, we've kept old columns in the table for a while).
- The "OpenJDK 16" sections need to be renamed "OpenJDK 17" (and any details changed if necessary)
- Any other platform changes, eg AIX 7.2 TL3 goes out of support at the end of September - what will our new TL level be? 
- Are there any changes to compiler levels?

**Comment by doveye** [comment]
Had a look at o/s levels:
- AIX 7.2 TL3 is going out of support at the end of the month - what do we change it to?
- RHEL 7.7 goes out of service in August (https://access.redhat.com/support/policy/updates/errata/) - what do we change it to?
- CentOS 6.10 reached end of maintenance Nov 2020 (https://wiki.centos.org/About/Product) - looks like this had been discussed in the past - do we want to keep it?

**Comment by keithc-ca** [comment]
Further down on the RHEL page under 'virtualization', it says RHEL 7 ELS ends June 30, 2026.
I'll defer to Peter on this.

**Comment by pshipton** [comment]
Pls change:
- AIX 7.2 TL3 to TL4
- RHEL 7.7 to 7.8
- CentOS 7.7 to 7.9
- CentOS 6.10 is a strange case, we're following Adopt's lead and continuing to build x86 JDK8,11 on this OS so it can still be used to run on. It can continue to be listed as supported.

**Comment by pshipton** [comment]
For build environments, pls change:
- JDK 17 Linux x86 64-bit to CentOS 7.9
- Linux on POWER LE 64-bit to CentOS 7.9
- Linux on "IBM Z 64-bit" to RHEL 7.9

**Comment by doveye** [comment]
@pshipton changes made, thanks. If you're happy with the updates, can you please merge https://github.com/eclipse-openj9/openj9-docs/pull/823.
