### ISSUE TITLE
Add documentation of new CML option-XX:[+|-]EnsureHashed:<class_name>

### ISSUE THREAD

**Issue by hangshao0** [eclipse-openj9/openj9-docs#826]
**Issue or pull request number:**
Issue: https://github.com/eclipse-openj9/openj9/issues/13029
Pull request: https://github.com/eclipse-openj9/openj9/pull/13338

**Overview:**
A new command line option is added to optimize the performance of hashCode() on objects of the given classes. 

**Release target:**
Eclipse OpenJ9 0.30.0

**Applies to the following JDK versions:**
All versions

**Applies to the following platforms:**
All platforms

**For new command line options:**

- Option name and syntax: -XensureHashed:<class_name>
- If values are set:  
	No default value.
- Purpose: Pass in class names so that JVM can optimize the performance of hashCode() on objects of these classes.
- Restrictions: N.A.

**Comment by EricYangIBM** [comment]
This issue should be updated to the new syntax `-XX:[+|-]EnsureHashed`
