### ISSUE TITLE
Please document that only the most recent -Xjit option takes effect

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9-docs#873]
**Subject:**

The [page on `-Xjit`](https://www.eclipse.org/openj9/docs/xjit/) does not note that only the most recent `-Xjit` option takes effect. In the following example, multiple separate `-Xjit` options are specified but only the last one takes effect:

```
$ podman run --rm ibm-semeru-runtimes:open-17-jdk sh -c "java -Xjit:verbose,exclude={ilog/rules/engine/sequential/generated/*} -Xjit:verbose,perfTool -version 2>&1 | awk '/INFO:  JIT/ {state=1;} state==1 && /options specified/ {state=2;} state==2 && /options in effect/ {state=0;} state==2 {print;}'"
#INFO:  options specified:
#INFO:       verbose,perfTool
#INFO:  
```

We see some customers using multiple `-Xjit` options without realizing this.

**Suggestion:**

Add a note that only the most recent `-Xjit` option takes effect. For example, maybe something along the lines of:

> The `-Xjit` option should only be specified once. If it's specified multiple times, only the last option takes effect. To specify multiple `-Xjit` parameters, use commas to separate the parameters; for example, `-Xjit:enableGPU,exclude={ilog/rules/engine/sequential/generated/*}`. Parameters such as `exclude` are additive and may be specified multiple times (but all within the same `-Xjit` option).

@JamesKingdon please confirm/modify

**Comment by JamesKingdon** [comment]
I believe that describes the current status, although since the behaviour is undefined it may be subject to change in the future.

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage
