### ISSUE TITLE
Upgrade OpenJ9 user docs to latest levels of build dependencies

### ISSUE THREAD

**Issue by doveye** [eclipse-openj9/openj9-docs#914]
To maintain currency, the OpenJ9 user documentation build toolchain must move up to a later level of core components and dependencies. This work is done every 9 -12 months. It's been a nearly 12 months since the last update (last issue was https://github.com/eclipse-openj9/openj9-docs/issues/754 but there was a later PR: https://github.com/eclipse-openj9/openj9-docs/pull/790).

The core components include MkDocs with the MkDocs material theme.

**Comment by doveye** [comment]
@AdamBrousseau We've tested with Ubuntu 20.04 (we tried 22.04 but it didn't work). If we change the build to use Ubuntu 20.04, does anything need to be changed in Jenkins, eg for the build to run on a different node?

**Comment by sujathamibm** [comment]
Tested on Ubuntu 20.04 with these levels - 
`click==8.1.3
    # via mkdocs
ghp-import==2.1.0
    # via mkdocs
importlib-metadata==4.11.3
    # via
    #   markdown
    #   mkdocs
jinja2==3.1.2
    # via
    #   mkdocs
    #   mkdocs-macros-plugin
    #   mkdocs-material
markdown==3.3.7
    # via
    #   mkdocs
    #   mkdocs-material
    #   pymdown-extensions
markupsafe==2.1.1
    # via jinja2
mergedeep==1.3.4
    # via mkdocs
mkdocs==1.3.0
    # via
    #   -r requirements.in
    #   mkdocs-macros-plugin
    #   mkdocs-material
mkdocs-macros-plugin==0.7.0
    # via -r requirements.in
mkdocs-material==8.2.14
    # via -r requirements.in
mkdocs-material-extensions==1.0.3
    # via mkdocs-material
packaging==21.3
    # via mkdocs
pygments==2.12.0
    # via mkdocs-material
pymdown-extensions==9.4
    # via mkdocs-material
pyparsing==3.0.8
    # via packaging
python-dateutil==2.8.2
    # via
    #   ghp-import
    #   mkdocs-macros-plugin
pyyaml==6.0
    # via
    #   mkdocs
    #   mkdocs-macros-plugin
    #   pyyaml-env-tag
pyyaml-env-tag==0.1
    # via mkdocs
six==1.16.0
    # via python-dateutil
termcolor==1.1.0
    # via mkdocs-macros-plugin
watchdog==2.1.7
    # via mkdocs
zipp==3.8.0
    # via importlib-metadata`

**Comment by sujathamibm** [comment]
Dockerfile changes - 
1. FROM ubuntu:20.04
2. During docker build `docker build -f Dockerfile -t ibmjavaid/mkdocs_test_env:latest`, there was an interruption in the configuring TZDATA step. It was asking for an user input (interactive) asking for timezone details. No matter what input I gave, the build was not progressing. 
To resolve this, in the Dockerfile, I had to add apt-get install -y tzdata in the first RUN statement as in -
`RUN apt-get update && apt-get install -y tzdata && apt-get install -y`

**Comment by AdamBrousseau** [comment]
> does anything need to be changed in Jenkins

No, I would expect the host nodes that it built on before would still work for newer Ubuntu versions.

**Comment by doveye** [comment]
Sujatha and I have been looking at this a lot recently. MkDocs is now up to 1.4.2 and Material 9.0.2. We've changed the Ubuntu level in the dockerfile from 18.04 to 22.04 and the Java version from 8 to 11, then tested with a new Docker image.

There are some changes in the dependencies that affect the docs. These changes need to be made in parallel with the updates to the new Docker image:

- Some of the icons in the font awesome package were renamed. We need to search the markdown files and make the following changes:
    - Pencil: `fontawesome-solid-pencil-alt` to `fontawesome-solid-pencil`
    - Times: `fontawesome-solid-times` to `fontawesome-solid-xmark`
    - Warning: `fontawesome-solid-exclamation-triangle` to `fontawesome-solid-triangle-exclamation`
- `docs.stylesheets/oj9.css` needs to be updated to change `md-footer-social` to `md-social`
- `theme/partials/footer.html` needs to be updated to delete the following lines from near the end (although the lines are inside a comment, parts were appearing in the output):
     ```
     <!--
          {% include "partials/social.html" %}
     -->
     ```

**Comment by doveye** [comment]
There are a couple of hardcoded paths to the Python directory in the build script, JenkinsFile_build_doc.groovy, which had to be updated because of the change to the Ubuntu level. We should find a better way of doing this. There were some also some mysterious "fatal: unable to create threaded lstat: Operation not permitted" errors in the staging build, which could possibly be caused by resource issues?

Everything seems to be working now though.
