### ISSUE TITLE
Delete sentence that says JITServer is tech preview on zLinux

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9-docs#927]
**Issue or pull request number:**
*https://github.com/eclipse-openj9/openj9/pull/14424*

**Overview:**
*Since we fixed the remaining bugs for JITServer on zLinux we can declare full support on this platform as well. Thus we shouls remove the sentence that says: "Note: On Linux on IBM Z systems, this feature is a technical preview and should not be used in production environments."*

**Release target:**
*Eclipse OpenJ9 0.32.0*

**Applies to the following JDK versions:**
*8, 11 and 17 (where JITServer is supported)*

**Applies to the following platforms:**
*Linux Z*

**Comment by doveye** [comment]
Doc updates are in as are updates to the release notes in the code repo, so this issue is done.
