### ISSUE TITLE
Change documentation to reflect JITServer support for openssl 3 when added

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9-docs#930]
**Issue or pull request number:**
*TBD*

**Overview:**
**

**Release target:**
*Eclipse OpenJ9 0.33.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P|Z *

**Comment by doveye** [comment]
Hi @mpirvu - is this still targeted for 0.33 or is it now 0.34?

**Comment by mpirvu** [comment]
@doveye The changes to version0.33.md are captured in this PR https://github.com/eclipse-openj9/openj9-docs/pull/962 created by @Sreekala-Gopakumar.
@Sreekala-Gopakumar could you please change 3.0 into 3.0.x in jitserver.md? Thanks

**Comment by Sreekala-Gopakumar** [comment]
@doveye, I have updated the documents with the changes as per this issue and committed the files. Could you please check and confirm the same. Thanks!
