### ISSUE TITLE
Document the JITServer custom metrics exporter for Prometheus

### ISSUE THREAD

**Issue by mpirvu** [eclipse-openj9/openj9-docs#952]
**Issue or pull request number:**
*https://github.com/eclipse-openj9/openj9/pull/14762*

**Overview:**
*JITServer offers the possibility of exporting a predefined set of custom performance metrics to monitoring tools that follow the OpenMetrics protocol, like Prometheus. New options were added to enable/disable this feature and to specify the port on which the metrics are exported*

**Release target:**
*E.g. Eclipse OpenJ9 0.33.0*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*Linux X|P|Z*

**New command line options:**

`-XX:[+|-]JITServerMetrics` enables/disables the export of custom metrics
`-XX:JITServerMetricsPort=<NNN>` specifies port number on which the metrics are provided (default 38500)

**Comment by Sreekala-Gopakumar** [comment]
Doc updates specified in this issue were done as a part of the AOT issue ([#953](https://github.com/eclipse-openj9/openj9-docs/issues/953)).

**Comment by doveye** [comment]
See comment on the AOT issue https://github.com/eclipse-openj9/openj9-docs/issues/953#issuecomment-1197952974
