### ISSUE TITLE
x64 default OS stack size update to 512k for jdk17+

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#959]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/15072

**Overview:**
The x64 default OS stack size is doubled from 256k to 512k on jdk17+ to accommodate vector support.

**Release target:**
OpenJ9 0.33

**Applies to the following JDK versions:**
Java 17 and later.

**Applies to the following platforms:**
xlinux, xmac, Windows

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse-openj9/openj9-docs/pull/965

**Comment by pshipton** [comment]
I meant to close my PR.

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
@doveye - I have incorporated the changes and corrected the line ending error. Could you please check. Thanks!

**Comment by doveye** [comment]
@Sreekala-Gopakumar the updates look fine to me. Please go ahead and squash the commits.

**Comment by Sreekala-Gopakumar** [comment]
@doveye, I have squashed the commits.

**Comment by doveye** [comment]
@pshipton do you want to check the updates again or are you happy for me to merge the PR?

**Comment by pshipton** [comment]
Checked and merged.
