### ISSUE TITLE
Update `-XcompilationThreads` option documentation

### ISSUE THREAD

**Issue by AlexeyKhrabrov** [eclipse-openj9/openj9-docs#966]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/pull/12914
https://github.com/eclipse-openj9/openj9/pull/12926

**Overview:**
The ranges of valid values for the `-XcompilationThreadsN` option have changed on both the JITServer and the JIT client. The server now supports up to 999 compilation threads, and the client (as well as the JVM not using JITServer) supports up to 16. The default number of threads is unchanged: 7 on the client on most platforms, 63 at the server. Increasing the maximum number of client threads can improve performance in high network latency settings since there can be more in-flight concurrent compilation requests. Increasing the number of threads at the server can improve performance if it has many CPU cores available and serves a large number of clients concurrently.

**Release target:**
Eclipse OpenJ9 0.33.0

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
All JITServer platforms: Linux X|P|Z

**Comment by AlexeyKhrabrov** [comment]
@mpirvu FYI

**Comment by AlexeyKhrabrov** [comment]
In addition to updating the `-XcompilationThreads` documentation, I think it might be helpful to also describe when and how to increase the number of threads from the default in the "JITServer tuning" page.

**Comment by Sreekala-Gopakumar** [comment]
@AlexeyKhrabrov, @mpirvu,  Could you please check the changes made and confirm. Thanks!

**Comment by pshipton** [comment]
Confirmed the changes are in 0.33

**Comment by Sreekala-Gopakumar** [comment]
@mpirvu - I have updated the documents based on your feedback. Please confirm the content is now fine.

**Comment by doveye** [comment]
Thanks, the changes look good. As this item was already approved, I'll go ahead and merge the PR.

**Comment by doveye** [comment]
Actually, can you squash the commits first please @Sreekala-Gopakumar

**Comment by doveye** [comment]
git refused to squash, the PR was merged, and the changes are now appearing on the draft server, so I'll close this issue.
