### ISSUE TITLE
IBM Java documentation still states that -Xshareclasses is disabled by default

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9-docs#971]
**Page containing the error:**

https://www.ibm.com/docs/en/sdk-java-technology/8?topic=sharing-introduction

> By default, class data sharing is not enabled.

However, the OpenJ9 docs state: https://www.eclipse.org/openj9/docs/xshareclasses/

> Class data sharing is enabled by default for bootstrap classes only (the equivalent of specifying `-Xshareclasses:bootClassesOnly,nonFatal,silent`), unless your application is running in a container.

**Describe the error and the update needed:**

Presumably the first link needs to be updated with the text of the second link.

**Comment by pshipton** [comment]
The first link is correct for IBM Java 8. With IBM Java 8, class data sharing is not enabled by default.

**Comment by kgibm** [comment]
Ahh, ok, thanks. Is there a list somewhere of default differences in JVM options?

**Comment by doveye** [comment]
When the OpenJ9 docs are re-used in the IBM SDK docs, they are modified for differences like that. There's a summary list in https://www.ibm.com/docs/en/sdk-java-technology/8?topic=openj9-user-documentation but actually this diff is not in there. We'll get it added.

**Comment by kgibm** [comment]
Thanks! While reading that page, I noticed another slight issue:

> For example, references to macOS® are not relevant, because there is no SDK for the macOS platform that includes the OpenJ9 VM.

There is a [Semeru/OpenJ9 SDK for macOS](https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?os=macOS), although there's no IBM SDK using OpenJ9 for macOS.

**Comment by doveye** [comment]
Sure, but those docs are for the IBM SDK only, and shouldn't mention Semeru. There aren't really any user docs for Semeru, since it's all open source, just a couple of migration guides. Semeru users should use the OpenJ9 docs.

**Comment by doveye** [comment]
Ok, I see what you're saying. Interpretation currently depends on what space your head is in when you read that sentence, so it could use a little extra clarification! I'll make it "IBM SDK".

**Comment by doveye** [comment]
I used the full product name, just to be really clear. Are you happy for this issue to be closed?

**Comment by kgibm** [comment]
Yes, thank you!

**Comment by doveye** [comment]
Thanks for helping to improve the docs :)
