### ISSUE TITLE
Document Update for Javadump threads section

### ISSUE THREAD

**Issue by yathamravali** [eclipse-openj9/openj9-docs#975]
**Issue or pull request number:**
*https://github.com/eclipse-openj9/openj9/pull/15555*
*https://github.com/eclipse-openj9/openj9/issues/284*

**Overview:**
*Currently javacore shows unowned for the threads waiting on java/lang/J9VMInternals$ClassInitializationLock. With the PR update the thread currently responsible for advancing the initialization of a class using a separate label(Initializing thread) is included in the output.*

**Release target:**
*Eclipse OpenJ9 0.35*

**Applies to the following JDK versions:**
*8 and later*

**Applies to the following platforms:**
*All platforms*

**Comment by yathamravali** [comment]
More details:
**Subject**: Add additional info to threads section, https://www.eclipse.org/openj9/docs/dump_javadump/#threads

**Suggestion**
With this PR https://github.com/eclipse-openj9/openj9/pull/15555, 

For the threads that are waiting(CW) on class init lock  (**java/lang/J9VMInternals$ClassInitializationLock**), an additional label **Initializing thread: $THREAD_NAME** is included in the output under **3XMTHREADBLOCK** section that shows the thread currently responsible for advancing the initialization of a class.

Example:
3XMTHREADBLOCK     Waiting on: java/lang/J9VMInternals$ClassInitializationLock@0x00000000FFF5DC90 Owned by: <unowned> Initializing thread: "Class Initialization Thread 1"

**Comment by Sreekala-Gopakumar** [comment]
I have started looking at this issue and will be updating the document.
