### ISSUE TITLE
Add OpenJDK 19 to release notes when confirmed

### ISSUE THREAD

**Issue by Sreekala-Gopakumar** [eclipse-openj9/openj9-docs#976]
When we know that 0.35 will support OpenJDK 19, ensure that it's added to the list of supported releases in the 0.35 What's New topic and the release notes in the code repo.

**Comment by Sreekala-Gopakumar** [comment]
Removed information regarding support for OpenJDK 18 from the What's New topic (0.35.0) as per the feedback received from Keith (https://github.com/eclipse-openj9/openj9-docs/pull/980#discussion_r955404333).

**Comment by doveye** [comment]
0.35 will not support Java 19, so I'm closing this issue.
