### ISSUE TITLE
Document new -Xdump user2 event for the SIGUSR2 signal

### ISSUE THREAD

**Issue by kgibm** [eclipse-openj9/openj9-docs#978]
**Issue or pull request number:**

* https://github.com/eclipse-openj9/openj9/issues/15636
* https://github.com/eclipse-openj9/openj9/pull/15637

**Overview:**
Add new `user2` `-Xdump` event driven by the `SIGUSR2` signal that is available on Linux X+P+Z, AIX, z/OS, and macOS. This provides users with additional flexibility to trigger `-Xdump` agents. There is a common need to split lightweight agents into one signal and heavyweight agents into another; for example:

```
-Xdump:system:events=user2,request=exclusive+prepwalk
```

**Release target:**
0.35

**Applies to the following JDK versions:**
8 and later

**Applies to the following platforms:**
Linux X+P+Z, AIX, z/OS, and macOS (i.e. all but Windows)

**For new command line options:**

- Option name and syntax:
    - New `-Xdump` `user2` event added. Defaults are not changed so this command line option must be used to utilize this new feature. Example:
      ```
      -Xdump:system:events=user2,request=exclusive+prepwalk
      ```
- Purpose: Additional `-Xdump` event triggered with the `SIGUSR2` signal; for example:
  ```
  kill -USR2 $PID
  ```
- Restrictions: Does not work on Windows

**Additional notes:**

I'm not sure if the following notes are worth documenting or not:

1. `-Xdump` defaults are not changed, so the user must specify `-Xdump:[...]:events=user2` to use this feature.
2. There is a minor behavior change in that, previously, sending `SIGUSR2` would cause the process to exit; now, the process does not exit in response to this signal.
3. The `java` agent behaves differently under the `user2` event compared to the `user` event: Under the `user` event, the `java` agent with `request=exclusive` shares exclusive access if another agent already has it whereas under the `user2` event, the `java` agent with `request=exclusive` will wait to acquire exclusive access for itself. The reason for this difference is that the default `java` agent may be used during a JVM deadlock situation to gather diagnostics when exclusive access won't be released; however, this causes a potential issue during non-deadlock situations of [gathering javacores that are not reliable](https://github.com/eclipse-openj9/openj9/issues/9256). The behavior difference of the `user2` event gives advanced users the flexibility to enforce `exclusive` access to gather reliable javacores under the assumption that the JVM has not deadlocked.

**Comment by kgibm** [comment]
@pshipton @keithc-ca fyi

**Comment by Sreekala-Gopakumar** [comment]
@doveye - I am updating the document to include this addition. Thanks!

**Comment by kgibm** [comment]
> I couldn't find any mention of this signal in the existing documents. It is not documented even in the Signal Handling topic (https://www.eclipse.org/openj9/docs/openj9_signals/). Any particular reason why it was not documented?

It wasn't documented because, previously, the signal wasn't handled by J9 and thus defaulted to killing the process (by the operating system).

> Should I add this SIGUSR2 signal in the "Signals on Linux, MacOs, AIX and Z/os" section tables of that topic?

Yes (in addition to updating the `-Xdump` page with the new `user2` agent).

> If yes, then could you please provide the other information related to this signal as displayed in the different columns of those tables (standard numerical value for that signal, Type, Description, Option to disable signal).

* [Signal](https://github.com/eclipse-openj9/openj9/blob/master/jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/SignalName.java):
    * AIX: 31
    * Linux: 12
    * macOS: 31
    * z/OS: 17
* Type: Int
* Description: "User-defined signal 2."
* Option to disable signal: `-Xrs`

**Comment by Sreekala-Gopakumar** [comment]
@kgibm - Thanks, Kevin for these details. I noticed that in the existing document, the description of SIGUSR1 is little more descriptive and varies for different systems (https://www.eclipse.org/openj9/docs/openj9_signals/):
Z/OS -> SIGUSR1 - Used by the java.net class library code
Mac/OS -> Used by the VM for thread introspection

Is it possible to have something similar for SIGUSR2 instead of a generic "User-defined signal 2." for all the applicable systems?
