### ISSUE TITLE
Windows jdk11 compilation uses VS2019

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#981]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/15582

**Overview:**
Windows jdk11 compilation uses VS2019 instead of VS2017

**Release target:**
Eclipse OpenJ9 0.35

**Applies to the following JDK versions:**
jdk11

**Applies to the following platforms:**
Windows

**Comment by doveye** [comment]
I'm going to ask Sreekala to take a look at this so she's familiar the next time one of these VS updates happens. I can't assign her until she adds a comment though, and she's off for most/all of this week.

**Comment by Sreekala-Gopakumar** [comment]
I will look at this, Esther.
