### ISSUE TITLE
We expect to remove AArch64 macOS from Early Access in 0.35

### ISSUE THREAD

**Issue by pshipton** [eclipse-openj9/openj9-docs#992]
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/11164

**Overview:**
We expect to remove AArch64 macOS from Early Access in 0.35. The build supports non-compressed references only, we expect to add compressed references support in a future release.

**Release target:**
 0.35

**Applies to the following JDK versions:**
Java 11 and later

**Applies to the following platforms:**
Aarch64 macOS

**Comment by pshipton** [comment]
@knn-k @0xdaryl fyi

**Comment by pshipton** [comment]
You can create the PR, I don't expect to merge it immediately.

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Can I go ahead? Thanks!

**Comment by pshipton** [comment]
Pls create the Pull Request with the changes.
